feature/footer-component
AxaFrance/design-system pull request #110
Opened 2024-02-01 08:55 UTC by Triki-Ahmed

Footer component : 
<img width="400" alt="footer" src="https://github.com/AxaFrance/design-system/assets/148236875/fa8a4fad-0043-4313-a151-73d9aaa702b3">

Related issue : #30

2024-02-02 07:46 UTC, GuillaumeKESTEMAN commented on packages/css/src/Layout/Footer/Footer.stories.ts
> +    footer.className = args.className ? args.className : "af-footer";
```suggestion
    footer.className = args.className ?? "af-footer";
```

2024-02-02 07:46 UTC, GuillaumeKESTEMAN commented on packages/react/src/Layout/Footer/Footer.mdx
> +<Canvas of={FooterStories.FooterStory}></Canvas>
```suggestion
<Canvas of={FooterStories.FooterStory} />
```

2024-02-02 15:32 UTC, pplancq requested changes

2024-02-02 15:32 UTC, pplancq commented on packages/css/src/Layout/Footer/Footer.scss
> +      height: $logo-size;
ici il ne faut pas mettre ?
```suggestion
      width: common.$logo-size;
      height: common.$logo-size;
```

2024-02-02 15:32 UTC, pplancq commented on packages/react/src/Layout/Footer/Footer.tsx
> +        {!!icon && (
```suggestion
        {Boolean(icon) && (
```

2024-02-02 15:39 UTC, Triki-Ahmed commented on packages/css/src/Layout/Footer/Footer.scss
> +      height: $logo-size;
Non enfaite Paul , `$logo-size` c'est une variable qui est déclaré en haut 
<img width="250" alt="var" src="https://github.com/AxaFrance/design-system/assets/148236875/387dc5e2-3f86-441e-abae-f743b68c4c68">

2024-02-02 15:41 UTC, pplancq commented on packages/css/src/Layout/Footer/Footer.scss
> +      height: $logo-size;
A oui décidément je suis vraiment une cruche en css.

2024-02-02 15:42 UTC, pplancq approved these changes, later dismissed

2024-02-05 07:36 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-02-08 14:29 UTC, SebastienDegodez approved these changes

2024-02-12 13:49 UTC, samuel-gomez commented on packages/react/src/Layout/Footer/Footer.tsx
> +    <footer ref={ref} className={className}>
on en profiterait pas pour permettre l'ajout de tous les autres attributs HTML natifs au footer ?

2024-02-12 13:49 UTC, samuel-gomez approved these changes, later dismissed

2024-02-12 14:31 UTC, Triki-Ahmed commented on packages/react/src/Layout/Footer/Footer.tsx
> +    <footer ref={ref} className={className}>
oui je vais le faire

2024-02-12 15:55 UTC, pplancq approved these changes

2024-02-12 17:35 UTC, SebastienDegodez approved these changes

2024-02-13 08:33 UTC, GuillaumeKESTEMAN approved these changes

2024-02-13 09:03 UTC, merged