Feature/component-restitution
AxaFrance/design-system pull request #142
Opened 2024-02-15 13:33 UTC by Triki-Ahmed

Related issue : #11 

Expose a component just like the https://axafrance.github.io/react-toolkit/latest/storybook/index.html?path=/story/components-restitution--default

2024-02-15 17:16 UTC, pplancq commented on packages/react/src/Restitution/HeaderRestitution.tsx
> +          {title && <span className="af-restitution__title-main">{title}</span>}
D’après le type le type est requis donc le test ici n’est pas utile

2024-02-15 17:16 UTC, pplancq commented on packages/react/src/Restitution/HeaderRestitution.tsx
> +          <span className="af-restitution__title-subtitle">{subtitle}</span>
Par contre ici le subtitle peut être undined donc il faudrait tester la présence

2024-02-15 17:16 UTC, pplancq commented on packages/react/src/Restitution/RestitutionList.tsx
> +  const li = values.map((value: string) => (
Pourquoi mettre dans une constante ?

2024-02-15 17:16 UTC, pplancq commented on packages/react/src/Restitution/SectionRestitutionRow.tsx
> +  children = null,
Ici le = null n’est pas utile

2024-02-16 07:50 UTC, johnmeunier commented on packages/react/src/Restitution/Restitution.mdx
> +                "Bris des glaces",
Bris de glace

2024-02-16 07:51 UTC, johnmeunier commented on packages/react/src/Restitution/Restitution.mdx
> +                "Bris des glaces",
Bris de glace

2024-02-16 07:52 UTC, johnmeunier commented on packages/react/src/Restitution/Restitution.mdx
> +                "Bris des glaces",
(je vais pas l'écrire à chaque fois mais ça revient encore à d'autres endroits)

2024-02-16 09:05 UTC, GuillaumeKESTEMAN commented on packages/react/src/Restitution/ArticleRestitution.tsx
> +    </article>
Si children est null ou undefined, est-il nécessaire d'afficher la balise `<article>` ?

2024-02-16 09:05 UTC, GuillaumeKESTEMAN commented on packages/react/src/Restitution/SectionRestitutionRow.tsx
> +      <div className={classNameContainer}>{children}</div>
La `div` ne sert à rien si children est null ou undefined non ?
Si c'est bien le cas tu peux faire :

```suggestion
      {children && (<div className={classNameContainer}>{children}</div>)}
```

2024-02-16 13:08 UTC, Triki-Ahmed commented on packages/react/src/Restitution/HeaderRestitution.tsx
> +          {title && <span className="af-restitution__title-main">{title}</span>}
Je pense ici la condition c'est par rapport a tout l'élément span qui contient du css et non pas par rapport juste le title , mais comme tu as dit le title est mentionné required  , alors soit je rend le title optionnel et je laisse la condition , sois en tant que prop required je supprime dans ce cas la condition

2024-02-19 07:46 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-02-19 08:23 UTC, JLou requested changes

2024-02-19 08:23 UTC, JLou commented on packages/react/src/Restitution/HeaderRestitution.tsx
> +          )}
```suggestion
          {subtitle ? (
            <span className="af-restitution__title-subtitle">{subtitle}</span>
          ) : null}
```

Ca va éviter le bug nul où la personne passe une valeur nullable qui sera affichée (comme un `0` par exemple)

2024-02-19 08:23 UTC, JLou commented on packages/react/src/Restitution/HeaderRestitution.tsx
> +        </div>
Idem ici. De manière générale, il faut éviter le `&&` et plutot utiliser un ternaire.

2024-02-20 14:32 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-02-22 15:54 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-02-23 08:14 UTC, pplancq commented on packages/react/src/Restitution/SectionRestitutionRow.tsx
> +      <div className={classNameContainer}>{children}</div>
Attention la condition que tu propose n'ai pas toujours vrais.
si je fait:
```javascript
<SectionRestitutionRow>
  {foo && <div>foo</div>
  {bar && <div>bar</dov>
</SectionRestitutionRow>
```
et que foo et bar valent false alors mon children cela un tableau [false, false] du coup la div cela présent alors que fonctionnement il n'y pas pas de children

Dans ce cas il faut passer par la fonction Children de react et faire comme ceci:
```javascript
{Children.toArray(childre).length !== 0 && ...}
```
La fonction Children.toArray, convertie le children en un tableau préfiltré dans null, false, undifined. 

note: si un des children est un Fragment il faudra le traiter autrement car c'est vue comme un children

2024-02-23 08:16 UTC, pplancq approved these changes, later dismissed

2024-03-11 14:42 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-03-15 08:29 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-03-22 08:24 UTC, pplancq approved these changes, later dismissed

2024-09-20 15:02 UTC, JLou approved these changes

2024-09-20 15:02 UTC, MartinWeb approved these changes

2024-09-20 15:02 UTC, merged