feat(client): radio component
AxaFrance/design-system pull request #145
Opened 2024-02-16 09:23 UTC by jmevel

<img width="229" alt="image" src="https://github.com/AxaFrance/design-system/assets/2572775/f41ed0e0-d9d0-4b71-959a-edaec30a9fa1">
<br />
<img width="497" alt="image" src="https://github.com/AxaFrance/design-system/assets/2572775/809de097-69f0-41d6-919c-57515926abf8">
<br />
<img width="269" alt="image" src="https://github.com/AxaFrance/design-system/assets/2572775/5d9a4781-fa66-46e4-9c10-7bc4d87a054e">

2024-02-19 08:13 UTC, JLou requested changes

2024-02-19 08:13 UTC, JLou commented on packages/css/src/Form/Radio/Client/Radio.scss
> +/* stylelint-disable no-descending-specificity */
peut-être éviter de disable des règles sur le nouveau code

2024-02-19 08:13 UTC, JLou commented on packages/css/src/Form/Radio/Client/Radio.scss
> +@use "../../../common/reboot.scss";
Peut-on se passer ce ces CSS qui sont spécifiques à slash, qu'à terme on voudrait à minima améliorer, au mieux supprimer ?

2024-02-19 08:13 UTC, JLou commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +export enum RadioModes {
à quoi servent ces modes ? Il ne semble pas y avoir de mode sur le look and feel

2024-02-19 12:56 UTC, jmevel commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +export enum RadioModes {
Finalement si, j'ai appelé Gwendaline et ces deux modes existent bien dans la liste des composants à créer. 
Il faut donc bien les garder mais en revanche mon code à besoin d'une petite évolution.

Screenshot des radios en mode `custom` et en mode `inline` juste en dessous

<img width="255" alt="image" src="https://github.com/AxaFrance/design-system/assets/2572775/7f3fb29a-8049-4b0c-aad9-fb87d278cd63">

2024-02-20 08:31 UTC, jmevel commented on packages/css/src/Form/Radio/Client/Radio.scss
> +@use "../../../common/reboot.scss";
Parfait. C'est supprimé

2024-02-20 08:36 UTC, jmevel commented on packages/css/src/Form/Radio/Client/Radio.scss
> +/* stylelint-disable no-descending-specificity */
Alors j'ai essayé de l'enlever mais je suis bloqué par deux erreurs qui je pense n'ont pas de sens (en tout cas pas en Sass)

>src/Form/Radio/Client/Radio.scss
 148:7  ✖  Expected selector ".af-form-client__radio-custom--disabled .af-form-client__description" to come before selector ".af-form-client__radio          no-descending-specificity
           .af-form-client__label .af-form-client__description"
 167:5  ✖  Expected selector ".af-form-client__radio-custom .af-form-client__description" to come before selector ".af-form-client__radio                    no-descending-specificity
           .af-form-client__label .af-form-client__description"
           
J'ai été obligé de remettre ce "disable" car meme la commande `npm run stylelint:fix` n'arrive pas a corriger ces deux erreurs.
Et comme le dit la [documentation de Stylelint](https://stylelint.io/user-guide/rules/no-descending-specificity/): `We recommend turning this rule off if you use a lot of nesting.`

Si c'est ok pour toi je ferme ce commentaire?

2024-02-20 14:31 UTC, jmevel commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +export enum RadioModes {
Le mode `custom` a évolué suivant le Figma et j'ai aussi ajouté une icone optionnelle sur tous les modes.

2024-02-20 14:32 UTC, jmevel commented on packages/css/src/Form/Radio/Client/Radio.scss
> +/* stylelint-disable no-descending-specificity */
Je ferme ce commentaire. Finalement suite a mes evolutions je n'ai plus d'erreur...

2024-02-20 15:40 UTC, samuel-gomez commented on packages/css/src/Form/Radio/Client/Radio.scss
> +      height: 3.44rem;
saurais-tu me dire pourquoi la hauteur est calculée sur la base de la taille de la font root ?

2024-02-20 15:42 UTC, samuel-gomez commented on packages/css/src/Form/Radio/Client/Radio.scss
> +    padding: 12px 16px;
idéalement, il faudrait utiliser les unités rem pour les margin et les padding car il y a un lien de proportionnalité avec la font root

2024-02-20 15:43 UTC, samuel-gomez commented on packages/css/src/Form/Radio/Client/Radio.scss
> +    max-width: 26.87rem;
il me semble qu'il existe une fonction rem() (à vérifier) qui permet de faire le calcul à partie d'une taille en px

2024-02-20 15:45 UTC, samuel-gomez commented on packages/css/src/Form/Radio/Client/Radio.scss
> +        font-size: 18px;
idem, mettre les tailles de police en rem

2024-02-20 15:45 UTC, samuel-gomez commented on packages/css/src/Form/Radio/Client/Radio.scss
> +/* stylelint-disable no-descending-specificity */
on ne pouvait pas résoudre le problème remonté par eslint ?

2024-02-20 15:54 UTC, jmevel commented on packages/css/src/Form/Radio/Client/Radio.scss
> +/* stylelint-disable no-descending-specificity */
Effectivement apres mes evolutions en CSS j'ai enfin reussi a corriger toutes les erreurs qu'il me sortait.
Le `disable` est supprimé du coup

2024-02-21 08:13 UTC, jmevel commented on packages/css/src/Form/Radio/Client/Radio.scss
> +    max-width: 26.87rem;
Je viens de vérifier. Il existe bien une function `rem()` mais celle-ci correspond à `remainder`, ce n'est pas lié aux pixels/rem. Il n'existe pas de function toute prête à utiliser. 
Je ferme ce commentaire

2024-02-21 08:19 UTC, GuillaumeKESTEMAN commented on packages/css/src/Form/Radio/Client/Radio.scss
> +    max-width: 26.87rem;
Je confirme qu'il y a bien une fonction rem() que j'ai dû modifier dans ma PR pour la rendre fonctionnelle : 
https://github.com/AxaFrance/design-system/pull/152/files#diff-03d78f234818ff4291e3183f30905a7d7488f7bbc1f110cef6648e037bcc27f2

2024-02-21 08:35 UTC, jmevel commented on packages/css/src/Form/Radio/Client/Radio.scss
> +    padding: 12px 16px;
Ca marche, c'est corrigé

2024-02-21 08:38 UTC, jmevel commented on packages/css/src/Form/Radio/Client/Radio.scss
> +      height: 3.44rem;
C'est remis en pixels. Je ne maitrise pas encore bien l'utilisation des `rem`.
Merci pour les explications dans les grandes lignes

2024-02-21 08:56 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +        const isChecked = option.value === value;
Pourquoi créer cette constante alors qu'elle n'a qu'une seule utilisation ?

2024-02-21 09:08 UTC, jmevel commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +        const isChecked = option.value === value;
Pour que le `return` soit plus concis et donc plus simple a lire d'un coup d'oeil.
Ca serait dur a lire si je devais mettre un switch case dans `div className={...}>`

C'est également ce qui est fait coté [radio agent](https://github.com/AxaFrance/design-system/blob/main/packages/react/src/Form/Radio/Radio.tsx#L39).

Ca te va ou bien tu veux vraiment supprimer cette constante?

2024-02-21 09:11 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +        const isChecked = option.value === value;
Ha non, je ne parlais pas de className, ça c'est bon pour moi. Github a dû mal afficher la ligne que je ciblais.
Je voulais parler de la constante `isChecked`

2024-02-21 09:13 UTC, jmevel commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +        const isChecked = option.value === value;
Ahhh autant pour moi, il m'avait échappé lui (copié collé du composant "Agent").
C'est corrigé 🙂

2024-02-21 09:19 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +      })}
Plus besoin du return désormais 😄

```suggestion
      {options.map((option: Option) => (
          <RadioItem
            {...otherProps}
            key={option.value}
            id={option.id}
            value={option.value}
            icon={option.icon}
            choice={option.label}
            description={option.description}
            isChecked={option.value === value}
            disabled={option.disabled || disabled}
            className={getItemClassNameMode(mode)}
            classModifier={classModifier}
          >
            {children}
          </RadioItem>
        )
      )}
```

2024-02-21 09:25 UTC, jmevel commented on packages/react/src/Form/Radio/Client/Radio.tsx
> +      })}
Haha bien vu !
C'est corrigé et j'en ai profité pour faire la meme refacto coté composant Agent 😉

2024-02-21 09:26 UTC, GuillaumeKESTEMAN approved these changes

2024-02-21 10:32 UTC, samuel-gomez approved these changes

2024-02-22 10:25 UTC, JLou approved these changes

2024-02-22 10:59 UTC, merged