fix: footer accessibility by tab + add utils/hook
AxaFrance/design-system pull request #160
Opened 2024-02-22 10:21 UTC by fffan64

added a hook to determine if we are in small screen or not
fixed the footer accessibility thanks to the hook

2024-02-22 10:53 UTC, JLou requested changes, later dismissed

2024-02-22 10:53 UTC, JLou commented on packages/react/src/Footer/MenuLink.client.tsx
> +          {...(isSmallScreen && !isAboutOpen && { tabIndex: -1 })}
ca fait mal à la tete cette syntaxe. je pense qu'etre plus explicite ca serait mieux 
```suggestion
          tabIndex={(isSmallScreen && !isAboutOpen) ? -1: null }
```

2024-02-22 10:53 UTC, JLou commented on packages/react/src/Utility/Hooks/useIsSmallScreen.ts
il aurait fallu créer ces dossiers en minuscule. La convention des majuscules c'est pour les composants normalement.

2024-02-23 07:25 UTC, GuillaumeKESTEMAN commented on packages/react/src/utilities/hooks/useIsSmallScreen.ts
> +      }
```suggestion
      setIsSmallScreen(window.innerWidth < breakPointToCheck);
```

2024-02-23 07:25 UTC, GuillaumeKESTEMAN commented on packages/react/src/utilities/hooks/useIsSmallScreen.ts
> +    const handler = () => {
Pourquoi définir une fonction dans le `useEffect` et pas en dehors ?
Tu pourrais par exemple la mettre dans le composant avec un `useCallback` et tu aurais le même comportement de reload de fonction quand `breakPointToCheck` changera de valeur.

2024-02-23 08:25 UTC, fffan64 commented on packages/react/src/utilities/hooks/useIsSmallScreen.ts
> +      }
merci

2024-02-23 08:45 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-02-27 13:19 UTC, pplancq commented on packages/react/src/Footer/MenuLink.client.tsx
> +  const isSmallScreen = useIsSmallScreen(1024);
d'où vient de breakPoint 1024 ?

2024-02-27 13:19 UTC, pplancq commented on packages/react/src/utilities/hooks/useIsSmallScreen.ts
> +  }, [breakPointToCheck, handler]);
ici le breakPointToCheck ne fait pas parti du useEffect donc ne doit pas faire partie des dépendence.
```suggestion
  }, [handler]);
```

2024-02-27 13:19 UTC, pplancq commented on packages/react/src/utilities/hooks/useIsSmallScreen.ts
> +  useEffect(() => {
Ici tu peux utiliser un useLayoutEffect cela te permet d'enregistré tes event plus rapidement car fait avec le rendu.

2024-02-27 13:19 UTC, pplancq commented on packages/react/src/utilities/hooks/useIsSmallScreen.ts
> +  }, [breakPointToCheck]);
ici l'appel au `setIsSmallScreen `va te générer de renderer superflu.
Voici une syntaxe plus optimiser
```suggestion
  const handler = useCallback(() => {
    const newState = window.innerWidth < breakPointToCheck;
    if (isSmallScreen !== newState) {
      setIsSmallScreen(newState);
    }
  }, [breakPointToCheck, isSmallScreen]);
```

D'ailleurs quitte à faire du react 18 autant même utiliser les nouvelles API et ce serait l'ocasion d'utiliser le useSyncExternalStore https://react.dev/reference/react/useSyncExternalStore#subscribing-to-a-browser-api

```typescript
const useIsSmallScreen = (breakPointToCheck: number) => {
  const subscribe = useCallback((listener: () => void) => {
    window.addEventListener('resize', listener);
    return () => {
      window.removeEventListener('resize', listener);
    };
  }, []);

  const getSnapshot = useCallback(() => {
    return window.innerWidth < breakPointToCheck;
  }, [breakPointToCheck]);

  return useSyncExternalStore(subscribe, getSnapshot);
};
```

2024-03-08 11:14 UTC, fffan64 commented on packages/react/src/utilities/hooks/useIsSmallScreen.ts
> +  }, [breakPointToCheck]);
je connaissais pas, top ! merci

2024-03-08 11:23 UTC, GuillaumeKESTEMAN commented on packages/react/src/Footer/MenuLink.client.tsx
> +  const isSmallScreen = useIsSmallScreen(1024);
Peut-être mettre un prop à place d'une valeur brute ?

2024-03-08 12:03 UTC, pplancq approved these changes, later dismissed

2024-03-08 12:03 UTC, pplancq commented on packages/react/src/utilities/hooks/useIsSmallScreen.ts
> +  return useSyncExternalStore(subscribe, getSnapshot);
J'y pense juste un dernier changement pour ceux qui refait du rendu serveur

```suggestion
const getServerSnapshot = useCallback(() => false, []);
  
  return useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot );
```

2024-03-08 12:06 UTC, fffan64 commented on packages/react/src/Footer/MenuLink.client.tsx
> +  const isSmallScreen = useIsSmallScreen(1024);
> Peut-être mettre un prop à place d'une valeur brute ?

du figma: 
![image](https://github.com/AxaFrance/design-system/assets/35838907/16be4757-155a-469f-a6ac-dc1da3be1028)

mais je c pas si c pertinent de la mettre en props et donc modifiable, car ca fait partie du design system lui meme je pense, donc je suis pour laisser comme ca, vous en pensez quoi @GuillaumeKESTEMAN  and @pplancq  ?

2024-03-08 12:08 UTC, pplancq commented on packages/react/src/Footer/MenuLink.client.tsx
> +  const isSmallScreen = useIsSmallScreen(1024);
Dans ce cas une constante me semble un bon compromis et cela évite d'avoir un magic number ;)

2024-03-08 12:57 UTC, pplancq approved these changes

2024-03-08 13:00 UTC, GuillaumeKESTEMAN approved these changes

2024-03-08 13:02 UTC, merged