feature: component form file
AxaFrance/design-system pull request #168
Opened 2024-02-26 16:17 UTC by JovaanB

- feat: add file component

2024-02-27 08:29 UTC, GuillaumeKESTEMAN requested changes
Il manque l'ajout de l'export scss dans le fichier `agent.scss`.
Par contre si cette PR correspond bien à cette issue : https://github.com/AxaFrance/design-system/issues/19 il manque la partie react non ?

2024-02-27 08:48 UTC, JovaanB commented
@GuillaumeKESTEMAN Bien vu 👍🏻 
Oui effectivement, comme pour le composant accordéon, notre projet est en CSS et Svelte, je laisse la partie React à quelqu'un d'autre

2024-02-27 08:53 UTC, GuillaumeKESTEMAN approved these changes

2024-03-28 15:20 UTC, Triki-Ahmed approved these changes

2024-10-04 07:38 UTC, GuillaumeKESTEMAN commented
File style and component created and merged in this PR : https://github.com/AxaFrance/design-system/pull/517

2024-10-04 07:38 UTC, closed without merging