feat(client): checkbox component
AxaFrance/design-system pull request #176
Opened 2024-02-29 10:02 UTC by jmevel

Mode `classic`
<img width="170" alt="image" src="https://github.com/AxaFrance/design-system/assets/2572775/a64d7ddb-0e68-4f42-a0ff-a4dd6a36068a">

Mode `custom`
<img width="512" alt="image" src="https://github.com/AxaFrance/design-system/assets/2572775/81950116-d35a-455f-bcfb-24427ecff983">

Mode `inline`
<img width="671" alt="image" src="https://github.com/AxaFrance/design-system/assets/2572775/03001305-0277-429b-8eb7-8ac6d52f2666">

2024-02-29 10:33 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-02-29 10:33 UTC, GuillaumeKESTEMAN commented on packages/css/src/Form/Checkbox/Client/Checkbox.stories.ts
> +       >
```suggestion
    <label class="af-form__group-label" for=":r2:">
        ${args.label}
    </label>
```

2024-02-29 10:33 UTC, GuillaumeKESTEMAN commented on packages/css/src/Form/Checkbox/Client/Checkbox.stories.ts
> +          >
```suggestion
       </label>
       <label class="af-form-client__checkbox-inline" for=":r2:">
```

2024-02-29 10:33 UTC, GuillaumeKESTEMAN commented on packages/css/src/Form/Checkbox/Client/Checkbox.stories.ts
> +          >
```suggestion
       </label>
       <label class="af-form-client__checkbox-inline" for=":r2:">
```

2024-02-29 10:33 UTC, GuillaumeKESTEMAN commented on packages/css/src/Form/Checkbox/Client/Checkbox.stories.ts
> +          >
```suggestion
       </label>
```

2024-02-29 13:36 UTC, jmevel commented on packages/css/src/Form/Checkbox/Client/Checkbox.stories.ts
> +       >
Effectivement, j'ai oublié de reformatter correctement ce bout de HTML. Tout est corrigé pour ce fichier

2024-02-29 14:05 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-03-01 09:15 UTC, JovaanB approved these changes

2024-03-01 09:32 UTC, buddyvegas approved these changes

2024-03-01 09:32 UTC, buddyvegas commented on packages/css/src/Form/Checkbox/Client/Checkbox.stories.ts
> +        <input label="Paris" name="placeName" class="af-form-client__input-checkbox" id=":r2:" type="checkbox" value="paris" />
pour l'accessibilité attention à ne pas répéter le label plusieurs fois, il sera lu autant de fois qu'il est présent (ici ça lira "Paris Paris Capitale de la France")
c'est un exemple pour le css ici mais j'ai l'impression que ce cas est présent aussi sur le composant React

2024-03-01 11:02 UTC, jmevel commented on packages/css/src/Form/Checkbox/Client/Checkbox.stories.ts
> +        <input label="Paris" name="placeName" class="af-form-client__input-checkbox" id=":r2:" type="checkbox" value="paris" />
Vu ensemble, cette PR c'est un premier jet. 
Une PR additionnelle pour les composants Radio et Checkbox viendra après

2024-03-04 07:47 UTC, GuillaumeKESTEMAN requested changes

2024-03-04 07:47 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Checkbox/Client/Checkbox.tsx
> +    onChange({ values: newValues, target: { value, checked }, id, name });
```suggestion
  }) => {
    const newValues = checked
      ? [...values, value]
      : values.filter((v) => v !== value);
    onChange({ values: newValues, target: { value, checked }, id, name });
```

2024-03-04 07:52 UTC, jmevel commented on packages/react/src/Form/Checkbox/Client/Checkbox.tsx
> +    onChange({ values: newValues, target: { value, checked }, id, name });
Oui tout a fait Guillaume. Désolé j'ai push des changements a la va vite vendredi soir pour faire une "sauvegarde".
Il y a un bug qui etait deja present coté checkbox "Agent" et que j'ai malheureusement sur mon composant car je suis reparti du meme code.
Il faut que je vois avec Samuel si j'arrive a l'avoir 😅
Je garde ce commentaire ouvert, ne pas merger cette PR pour le moment

2024-03-06 12:38 UTC, jmevel commented on packages/react/src/Form/Checkbox/Client/Checkbox.tsx
> +    onChange({ values: newValues, target: { value, checked }, id, name });
Corrigé. Finalement le comportement étrange que je constatais autant coté Agent que Client est inhérent a l'utilisation de StoryBook. 
Par ailleurs concernant ce bout de code que j'avais recopié du composant Agent, nous avons finalement décidé avec Rémy de le supprimer pour le moment et de créer au moins dans un premier temps un composant un peu plus "stupide" que son equivalent coté Agent afin de laisser une plus grande souplesse a l'utilisation par les consommateurs de ce composant et ne pas les "brider" a un fonctionnement spécifique.

2024-03-06 13:00 UTC, samuel-gomez commented on packages/react/src/Form/Checkbox/Client/Checkbox.tsx
> +  return (
le return n'est pas utile

2024-03-06 13:01 UTC, samuel-gomez commented on packages/react/src/Form/Checkbox/Client/CheckboxInput.tsx
> +import { ComponentProps, ReactNode } from "react";
import type

2024-03-06 13:01 UTC, samuel-gomez commented on packages/react/src/Form/Checkbox/Client/CheckboxInput.tsx
> +  return (
pas besoin de return

2024-03-06 13:02 UTC, samuel-gomez commented on packages/react/src/Form/Checkbox/Client/CheckboxItem.tsx
> +        ? `${baseClassName} ${defaultClassName}--disabled`
ça ne devrait pas plutôt être ça ?
```suggestion
        ? `${baseClassName} ${baseClassName}--disabled`
```

2024-03-06 13:08 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Checkbox/Client/CheckboxItem.stories.tsx
> +  render: ({ onChange, ...args }) => (
onChange fera parti de args si tu ne le précise pas.
Pourquoi le déclarer ?

2024-03-06 13:32 UTC, jmevel commented on packages/react/src/Form/Checkbox/Client/CheckboxItem.tsx
> +        ? `${baseClassName} ${defaultClassName}--disabled`
Bien vu. Corrigé !

2024-03-06 13:37 UTC, jmevel commented on packages/react/src/Form/Checkbox/Client/CheckboxItem.stories.tsx
> +  render: ({ onChange, ...args }) => (
Bien vu. C'est du code que j'ai copié de slash mais j'ai oublié de supprimer ce truc inutile. 
C'est corrigé 🙂

2024-03-06 13:46 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Checkbox/Client/Checkbox.tsx
> +        value={option.value}
Option passe déjà ces paramètres au dessus normalement
```suggestion
        className={getItemClassNameMode(mode)}
        checked={values ? values.indexOf(option.value) >= 0 : false}
        name={name}
        disabled={option.disabled || disabled}
```

2024-03-06 14:00 UTC, jmevel commented on packages/react/src/Form/Checkbox/Client/Checkbox.tsx
> +        value={option.value}
C'est exact 😅

2024-03-06 14:05 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-03-08 10:13 UTC, fffan64 approved these changes

2024-03-08 10:13 UTC, GuillaumeKESTEMAN approved these changes

2024-03-08 10:13 UTC, merged