feat: add alert client component
AxaFrance/design-system pull request #204
Opened 2024-03-13 15:21 UTC by fffan64

![image](https://github.com/AxaFrance/design-system/assets/35838907/f6739e4a-e574-4cae-8457-cad2562ec66e)

2024-03-13 15:51 UTC, buddyvegas approved these changes, later dismissed

2024-03-14 08:42 UTC, jmevel requested changes

2024-03-14 08:42 UTC, jmevel commented on packages/css/src/Alert/Alert.client.stories.ts
> +      return '<svg class="af-alert__icon" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="WbIncandescentOutlinedIcon"><path d="m3.55 19.09 1.41 1.41 1.79-1.8-1.41-1.41zM11 20h2v
On est pas censé utiliser Material plutôt que de créer nous-meme les SVG ?

2024-03-14 08:42 UTC, jmevel commented on packages/css/src/Alert/Alert.client.stories.ts
> +  | "neutral";
C'est les memes valeurs avec la const `MODIFIERS`. On ne peut pas unifier les deux plutot?

2024-03-14 08:42 UTC, jmevel commented on packages/css/src/Alert/Alert.client.stories.ts
> +  | "neutral";
Ah je n'avais pas vu que c'etait juste juste un fichier `stories` du coup c'est beaucoup moins important. 
Tu peux ignorer mon commentaire si tu veux

2024-03-14 08:42 UTC, jmevel commented on packages/react/src/Alert/Alert.client.mdx
> +There are 5 type available for the Alert component :
`5 types` 😉

2024-03-14 08:42 UTC, jmevel commented on packages/react/src/Alert/Alert.client.stories.tsx
> +// export const DangerAlert: StoryObj<typeof Alert> = {
Tu gardes ca en commentaire? Une autre PR viendra plus tard?

2024-03-14 08:53 UTC, fffan64 commented on packages/css/src/Alert/Alert.client.stories.ts
> +      return '<svg class="af-alert__icon" focusable="false" aria-hidden="true" viewBox="0 0 24 24" data-testid="WbIncandescentOutlinedIcon"><path d="m3.55 19.09 1.41 1.41 1.79-1.8-1.41-1.41zM11 20h2v
c le css la, on sen fiche ^^

2024-03-14 08:55 UTC, fffan64 commented on packages/react/src/Alert/Alert.client.stories.tsx
> +// export const DangerAlert: StoryObj<typeof Alert> = {
oublie de virer, merci ^^

2024-03-14 09:04 UTC, buddyvegas approved these changes

2024-03-14 09:12 UTC, jmevel approved these changes

2024-03-14 09:12 UTC, merged