fix(icons): remove export of @mui/icons-material
AxaFrance/design-system pull request #279
Opened 2024-04-17 14:30 UTC by buddyvegas

2024-04-17 14:47 UTC, fffan64 approved these changes

2024-04-17 14:50 UTC, fffan64 requested changes
en attente autre PR

2024-04-19 09:22 UTC, jmevel approved these changes

2024-04-25 09:32 UTC, GuillaumeKESTEMAN approved these changes

2024-04-30 07:13 UTC, fffan64 commented
plus besoin, je close

2024-04-30 07:13 UTC, closed without merging