feat: remplacement de @mui/icons-material par @material-design-icons/svg
AxaFrance/design-system pull request #280
Opened 2024-04-17 15:01 UTC by pplancq

Hello,

suppression de la lib `@mui/icons-material` car bien trop lourd et l'export des icones n'est pas "tip top".

Au lieu de cela je préconise l'utilisation de `@material-design-icons/svg` qui est en `peerDependencies optional` (donc ne sera pas installer par défaut) c'est au client d'installer cette lib ou un autre équivalente.

Pour l'utilisation des icones svg rien de plus simple, 
```typescript
import home from "@material-design-icons/svg/outlined/home.svg";
import { Svg } from "@axa-fr/design-system-react/client";

const App = () => {
    return (
        <Svg src={home} alt="home"/>
    )
}
```

Ici le composant Svg fonctionne comme une balise `img` il chargera au runtime le svg puis l'injectera directement dans le dom.
la props alt sert pour au cas ou le svg ne peut être affiché avoir un texte de fallback, qui à dit a11y ....

2024-04-17 15:25 UTC, fffan64 commented on packages/react/src/Icons/Icon.client.stories.tsx
> +// export const AllIcons: StoryObj = {
on peut tout enlever du coup je pense ?
ou alors mettre une story pour les icones quon gere nous, les SNS par exemple

2024-04-17 15:32 UTC, fffan64 commented on packages/react/tsconfig.json
> +  "include": ["src", "src/Icons/svg/facebook.svg"],
`/svg/*.svg` ?

2024-04-17 15:51 UTC, pplancq commented on packages/react/src/Icons/Icon.client.stories.tsx
> +// export const AllIcons: StoryObj = {
Yes je vais ramener cette storie dans le composant Svg

2024-04-17 15:51 UTC, pplancq commented on packages/react/tsconfig.json
> +  "include": ["src", "src/Icons/svg/facebook.svg"],
oups c'est un test qui ne de devrait pas rester ici

2024-04-18 07:05 UTC, Triki-Ahmed approved these changes, later dismissed

2024-04-18 07:19 UTC, fffan64 requested changes
juste par rapport au petite modif qu'il reste a faire

2024-04-18 08:44 UTC, pplancq commented on packages/react/src/Icons/Icon.client.stories.tsx
> +// export const AllIcons: StoryObj = {
done

2024-04-18 09:02 UTC, pplancq commented on packages/react/tsconfig.json
> +  "include": ["src", "src/Icons/svg/facebook.svg"],
done

2024-04-18 09:15 UTC, fffan64 approved these changes, later dismissed

2024-04-19 13:01 UTC, pplancq commented
J'ai été obligé d'update le composant svg car le svgInjector remplace à chaud l'élément html dans le dom ce qui contrarie un peux react qui n'arrive plus a retrouve ces petit.
du coup je passe par un dic qui fait aussi de wrapper en display: contents donc même si elle est présente dans le dom elle n'a pas d'impact sur le style.

et via le useLayoutEffect je charge à la mano un element svg qui servira à l'injection du svg mais du coup il n'est pas lié à réact

2024-04-22 06:11 UTC, fffan64 approved these changes, later dismissed

2024-04-22 13:03 UTC, fffan64 approved these changes

2024-04-23 12:20 UTC, Triki-Ahmed approved these changes

2024-04-23 14:10 UTC, merged