build(react): add react storybook
AxaFrance/design-system pull request #41
Opened 2023-12-19 15:38 UTC by JLou

2023-12-19 16:02 UTC, samuel-gomez-axa submitted a review, later dismissed

2023-12-20 09:40 UTC, MartinWeb approved these changes, later dismissed

2023-12-20 09:40 UTC, MartinWeb commented on packages/react/src/Button/Button.tsx
> +import "@axa-fr/design-system-css/src/Button/Button.agent.scss";
on a déjà un package pour cela à l'heure actuelle ?

2023-12-20 09:41 UTC, pplancq requested changes

2023-12-20 09:41 UTC, pplancq commented on packages/css/package.json
> +    "rimraf": "5.0.5"
ce sont de dépendance de dev

2023-12-20 09:41 UTC, pplancq commented on packages/react/package.json
> +    "@types/react": "18.2.43",
A mettre en devDependencies

2023-12-20 09:41 UTC, pplancq commented on packages/react/src/Button/Button.tsx
> +      className={cx("af-btn", classModifier && `af-btn--${classModifier}`)}
Ajoutons nous la possibilité dans cette version que si on ajoute une className que cela ne retire pas les classe de base ?

En plus je ne suis pas fan du classModifier car pas compatible avec le css module.
Pourquoi ne pas utiliser une props variant qui celons la valeur ajoute la classe qui va bien ?

2023-12-20 09:41 UTC, pplancq commented on packages/react/src/Button/Button.stories.tsx
> +    <Button classModifier={classModifier.join(" ")} onClick={onClick} {...args}>
ici impossible de mettre une liste de modifier.
sois il faut le retirer de la storie 
sois changer l'implem du bouton car on a 
```javascript
classModifier && `af-btn--${classModifier}`
```

2023-12-20 09:41 UTC, pplancq commented on packages/react/src/Button/Button.tsx
> +export { Button };
si on fait de l'export nommer pourquoi de pas mettre l'export ligne 9 au moment de la déclaration du bouton

2023-12-20 09:43 UTC, pplancq commented on packages/react/src/Button/Button.tsx
> +import "@axa-fr/design-system-css/src/Button/Button.agent.scss";
Non mais il faut partir du `dist `car le src ne sera pas dans le package final

2023-12-20 12:18 UTC, JLou commented on packages/react/src/Button/Button.tsx
> +export { Button };
J'ai pris cette habitude de toujours mettre les exports en bas de fichier, ca m'évite de chercher. Mais je peux le mettre devant la décla du composant, ça ne change rien.

2023-12-20 12:18 UTC, JLou commented on packages/react/src/Button/Button.stories.tsx
> +    <Button classModifier={classModifier.join(" ")} onClick={onClick} {...args}>
yep c'est l'implem du bouton qui était pas bonne

2023-12-20 12:29 UTC, pplancq commented on packages/react/src/Button/Button.stories.tsx
> +    <Button classModifier={classModifier.join(" ")} onClick={onClick} {...args}>
Je suis un partisan de moins j'en écrit mieux de me porte, après je te rejoint sur le coté lisibilité

2023-12-20 12:29 UTC, pplancq commented on packages/react/src/Button/Button.tsx
> +export { Button };
Je suis un partisan de moins j'en écrit mieux de me porte, après je te rejoint sur le coté lisibilité

2023-12-20 12:30 UTC, JLou commented on packages/react/src/Button/Button.tsx
> +import "@axa-fr/design-system-css/src/Button/Button.agent.scss";
j'ai fait un npm link, c'est pour ca que ca marche, meme si le package n'est aps encore publié

2023-12-20 12:33 UTC, pplancq commented on packages/react/src/Button/Button.tsx
> +import "@axa-fr/design-system-css/src/Button/Button.agent.scss";
Normalement tu n'as pas besoin dans le cadre d'un workspace npm, npm fait la résolution automatiquement.
Juste il faut penser à build le css pour que le dossier `dist `sois présent

2023-12-20 12:35 UTC, JLou commented on packages/react/src/Button/Button.tsx
> +      className={cx("af-btn", classModifier && `af-btn--${classModifier}`)}
j'ai rajouté pour l'instant mais faudra s'assurer que ce "bug" n'est pas exploité dans la nature avant de release en 1.0.0

2023-12-20 12:38 UTC, pplancq commented on packages/react/src/Button/Button.tsx
> +      className={cx("af-btn", classModifier && `af-btn--${classModifier}`)}
Quel bug ? j'en vois aucun.

2023-12-20 13:21 UTC, JLou commented on packages/react/src/Button/Button.tsx
> +      className={cx("af-btn", classModifier && `af-btn--${classModifier}`)}
Le fait que passer une classname écrase celles du design system... Ce dont on est en train de discuter 🤔

2023-12-20 14:57 UTC, pplancq commented on packages/react/src/Button/Button.tsx
> +import "@axa-fr/design-system-css/src/Button/Button.agent.scss";
pour moi ce la va planter lors de la mise en prod donc c'est pas résolue

2023-12-20 14:57 UTC, pplancq approved these changes

2023-12-20 14:57 UTC, MartinWeb approved these changes

2023-12-20 15:08 UTC, merged