feat(glyphicons): add glyphicons
AxaFrance/design-system pull request #46
Opened 2024-01-02 13:34 UTC by JLou

System: _Agent_
Older icons components using glyphicons are still widely used. This commit adds the glyphicons font. It also updated the Button stories to show how to use them.

The agent button should now be feature-complete matching its existing implementation.

fixes #1

2024-01-03 16:30 UTC, samuel-gomez-axa commented on packages/css/src/Button/Button.agent.scss
> +  .glyphicon {
cette classe ne sera pas forcément utilisée que pour les boutons, du coup je me demande si c'est le bon endroit pour ce code

2024-01-03 16:33 UTC, samuel-gomez-axa commented on packages/react/src/Button/Button.agent.scss
> +@use "@axa-fr/design-system-css/dist/Button/Button.agent.scss";
chez moi l'import direct dans le composant fonctionne, je ne me souviens quel problème tu avais rencontré

2024-01-03 16:38 UTC, samuel-gomez-axa commented on packages/react/src/Button/Button.agent.tsx
>  import { ComponentPropsWithoutRef, PropsWithChildren } from "react";
je vois que tu as renommé le composant en Button.agent.tsx, ne faudrait-il pas sortir le code React dans un fichier Button.tsx pour avoir une code base commune ?

2024-01-04 13:30 UTC, JLou commented on packages/react/src/Button/Button.agent.scss
> +@use "@axa-fr/design-system-css/dist/Button/Button.agent.scss";
C'est l'import des font qui déconnait. Pas les styles en eux meme. Vite venait pas bundle l'asset statique quand il tombait sur mes url("./XXX")

2024-01-04 14:43 UTC, JLou commented on packages/css/src/Button/Button.agent.scss
> +  .glyphicon {
Ici c'est le css pour placer l'icone dans le bouton. Tu voudrais externaliser ca ?

2024-01-05 07:02 UTC, pplancq requested changes

2024-01-05 07:02 UTC, pplancq commented on packages/css/package.json
> +    "build": "rimraf dist  && copyfiles --up 1 \"./src/**/*.scss\" ./dist/ && copyfiles  --flat \"./src/common/glyphicons/*\" ./dist/glyphicons && copyfiles  --flat \"./src/common/glyphicons/*\" ./di
Juste pour ne pas oublier de changer les copies files dans ma PR car j'ai utilisé postcss pour build les asset.

2024-01-05 07:02 UTC, pplancq commented on packages/react/src/Button/glyphicons/icons.eot
Pourquoi remettre les glyphicons dans le package react elles sont déjà présente dans le package css ?

2024-01-05 07:02 UTC, pplancq commented on packages/react/src/Button/Button.agent.tsx
>  import { ComponentPropsWithoutRef, PropsWithChildren } from "react";
Je suis d'accord, je pensais qu'a la base c'est le fichier source d'importation qui détermine le style agent ou client.
Du coup cela voudra dire que l'on aura un Button.client.tsx puis idem pour tous les autres composants cela va être très très lourd non ?

2024-01-05 07:02 UTC, pplancq commented on packages/react/src/Button/Button.agent.tsx
> +import "./Button.agent.scss";
Je ne comprend pas trop ce changement, surtout que le fichier scss à juste un use donc un import est suffisent pour moi

2024-01-05 07:04 UTC, pplancq commented on packages/css/src/Button/Button.agent.scss
> +  .glyphicon {
Je suis d'accord ici c'est juste un surcharge de la class si on est dans un af-btn pour placer l'icone je doute que cela sois utiliser ailleurs.

2024-01-05 14:18 UTC, pplancq commented on packages/react/src/Button/Button.agent.scss
> +@use "@axa-fr/design-system-css/dist/Button/Button.agent.scss";
suite a l'update des icones dans le agent.ts est ce toujours utile d'avoir ce fichier scss ?

2024-01-05 14:24 UTC, JLou commented on packages/react/src/Button/glyphicons/icons.eot
bien vu, c'etait un des tests que j'avais fait pour résoudre mon probleme de bundle.
Mais plus besoin maintenant !

2024-01-05 14:26 UTC, JLou commented on packages/react/src/Button/Button.agent.tsx
>  import { ComponentPropsWithoutRef, PropsWithChildren } from "react";
@samuel-gomez-axa vu ensemble, pour les composants simples pas besoin.
@pplancq je n'ai pas compris ton commentaire 😵‍💫. On aura tjrs besoin d'un fichier *.agent.tsx et client.tsx au moins pour l'import du style. Pour les composants complexes, on mettra ptetre la structure html dans un fichier commun, mais on ne pourra pas faire autrement qu'avoir 2 versions.

2024-01-05 14:26 UTC, JLou commented on packages/react/src/Button/Button.agent.scss
> +@use "@axa-fr/design-system-css/dist/Button/Button.agent.scss";
C'est corrigé !

2024-01-05 14:31 UTC, pplancq commented on packages/react/package.json
> +    "build": "tsc && copyfiles -u 1 src/**/*.scss dist/"
DU coup ici plus besoin de copyyfiles vue qu'il n'y a plus de scss.

2024-01-05 14:33 UTC, pplancq commented on packages/react/src/Button/Button.agent.tsx
>  import { ComponentPropsWithoutRef, PropsWithChildren } from "react";
Dans ce cas le composant ne ce nomme pas Button Mais ButtonAgent et idem pour le dossier.
D'ailleurs le src devrait être divisé en 3 folder Agent, Client et Common pour plus de clarter.

2024-01-05 14:33 UTC, JLou commented on packages/react/package.json
> +    "build": "tsc && copyfiles -u 1 src/**/*.scss dist/"
exact, fixed

2024-01-05 14:44 UTC, JLou commented on packages/react/src/Button/Button.agent.tsx
>  import { ComponentPropsWithoutRef, PropsWithChildren } from "react";
pour le découpage, les 2 sont possibles. Soit on découpe pas Design System, soit par composant. On est encore tot dans le dev donc si on estime que l'un est mieux que l'autre on avisera à ce moment. Attendons d'avoir un peu de matière pour en être sur.
Pour le nommage, non il ne faut pas que le composant soit `ButtonAgent` car 
1. c'est pas le nom actuel => breaking change
2. Le but c'est que le nom soit découplé du ds utilisé car c'est utilisé comme ca: `import {Button} from "@axa-fr/design-system-react/agent` 
3.

2024-01-05 14:49 UTC, pplancq commented on packages/react/src/Button/Button.agent.tsx
>  import { ComponentPropsWithoutRef, PropsWithChildren } from "react";
il n'y a pas de breaking change car le agent.ts lui exportera le ButtonAgent sous le nom de Button

2024-01-05 14:50 UTC, samuel-gomez-axa approved these changes

2024-01-05 14:52 UTC, pplancq approved these changes

2024-01-08 08:10 UTC, merged