Feat(client): permit to click item to be a link
AxaFrance/design-system pull request #469
Opened 2024-08-14 07:37 UTC by GuillaumeKESTEMAN

Issue : https://github.com/AxaFrance/design-system/issues/462

(I took advantage of the creation of ClickItem to review the management of classes and this corresponds to the following issue : https://github.com/AxaFrance/design-system/issues/401)

2024-08-14 07:48 UTC, samuel-gomez-axa commented on slash/css/src/List/ClickList/ClickList.client.scss
> +  border-radius: 4px;
ce serait pas mal de créer un token pour le radius

2024-08-14 07:54 UTC, GuillaumeKESTEMAN commented on slash/css/src/List/ClickList/ClickList.client.scss
> +  border-radius: 4px;
Si je le fais dans ma PR ça fera beaucoup de modifications supplémentaires 😅 
Tu veux que je crée une issue ? (normalement j'aurais le temps de m'en occuper aujourd'hui)

2024-08-14 09:30 UTC, samuel-gomez-axa commented on slash/css/src/List/ClickList/ClickList.client.scss
> +  border-radius: 4px;
tu peux faire une issue

2024-08-14 09:33 UTC, samuel-gomez-axa submitted a review, later dismissed

2024-08-14 09:42 UTC, GuillaumeKESTEMAN commented on slash/css/src/List/ClickList/ClickList.client.scss
> +  border-radius: 4px;
Issue créée : https://github.com/AxaFrance/design-system/issues/470

2024-08-14 10:03 UTC, buddyvegas requested changes

2024-08-14 10:03 UTC, buddyvegas commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
ça serait pas mieux avec 2 composants séparés ?
comme ça c'est pas géré en fonction des props mais c'est explicitement indiqué à l'utilisation
par exemple : `<ButtonItem>` et `<LinkItem>`

ça permet aussi de gérer le css plus facilement entre les 2 cas

2024-08-14 10:08 UTC, GuillaumeKESTEMAN commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
Le css est le même dans les 2 cas, c'est juste la balise qui change afin d'éviter d'utiliser un navigate sur un bouton et pouvoir bénéficier des comportements natif des liens.

2024-08-14 12:56 UTC, GuillaumeKESTEMAN commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
D'ailleurs on ne peut pas désactiver les balises a, comment comptes-tu gérer ce cas avec tes deux composants ?

2024-08-19 09:34 UTC, buddyvegas commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
si t'as besoin de désactiver un lien c'est que c'est juste du text, faut le prendre en compte dans le composant
là t'as par moment un lien, par moment un bouton et un 3ème cas avec un bouton disabled si tu met l'attribut en plus du href
si le css est exactement le même rien ne t'empêche de faire référence au même fichier css dans les composants
mais changer la balise HTML à la volée en fonction des props je trouve qu'on perd la maitrise de ce composant

2024-09-02 08:09 UTC, GuillaumeKESTEMAN commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
Ok pour la désactivation, je vais faire ça 👍 
Normalement dans le code final le développeur est censé mettre un lien ou non et cela définira la balise de ce composant, il n'est pas censé changer en cours de route. (sauf dans le cas du disabled pour le moment mais je vais mettre à jour cela).
Je trouve que ça fait un peu lourd d'avoir deux composants pour un seul avec des noms qui peuvent porter à confusion avec d'autres composants.

2024-09-02 10:00 UTC, GuillaumeKESTEMAN commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
Pour la désactivation c'est bon : https://github.com/AxaFrance/design-system/pull/469/commits/61fc2b70bbf6b18639dc940b8c3bba6a0510d30f

2024-09-09 12:50 UTC, buddyvegas commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
je vois pas de scenario où t'as une liste avec un mélange de bouton et de lien href
jouer avec la balise HTML en fonction des props je trouve que c'est le bordel, le design system est juste un ensemble de brique, après c'est aux projets de les utiliser comme ça lui convient
si on commence à faire ce genre de traitement ça peut dégénérer et on se retrouve avec des éléments peu modulable selon les besoins du projet

on peut en discuter sur la conv design system si tu préfères, on peut prendre l'avis de toute le monde

2024-09-11 07:26 UTC, GuillaumeKESTEMAN commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
En effet.
Concernant les scénarios je suis d'accord, j'ai surtout externalisé le composant de la liste car j'ai des cas où on aura une liste avec des éléments textuels et des ClickItems.

Je suis aussi d'accord qu'en agissant comme cela ça fait un mécanisme implicite aux yeux des développeurs qui l'utilisent.
Je ne voulais pas faire 2 composants car ça dupliquerais du code juste pour remplacer une balise `<button>` par `<a>`.
Il faudrait donc trouver un moyen de ne pas dupliquer de code et de pouvoir gérer facilement le passage de bouton à lien.

2024-09-11 13:38 UTC, buddyvegas commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
pour le code dupliqué c'est léger et ça reste 2 comportement différents de toute façon, au final c'est peut-être les class CSS qui vont se répéter, mais même à ce niveau là on est sur 2 éléments HTML différents on devrait avoir peu de css en commun

2024-09-11 14:17 UTC, jmraxa commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
> +    label: ReactNode;
**suggestion :** pourquoi ne pas simplement utiliser `children` de sorte à avoir un usage comme ceci : `<ClickItem>Mon label</ClickItem>` ?

2024-09-11 14:22 UTC, GuillaumeKESTEMAN commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
> +    label: ReactNode;
Je suis d'accord.
Le seul problème c'est que ça va faire un breaking change 🤔

2024-09-11 14:33 UTC, jmraxa commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
Je serai plutôt pour un seul composant et surtout garder le nom `ClickItem` qui match avec les termes utilisés par les UX/UI (y compris pour l'app mobile).

<img width="880" alt="image" src="https://github.com/user-attachments/assets/d81151de-7b61-45a4-b178-3537a6b79d29">

2024-09-12 10:07 UTC, buddyvegas commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
2 contre 1, je close la discussion ici pour le moment mais on peut continuer à en parler sur la conv dédiée
c'est plus un débat de fond sur comment on architecture le design system (on mache un peu le travail ou on fourni des briques simples pour construire une app avec le design axa)

2024-09-12 10:07 UTC, buddyvegas approved these changes, later dismissed

2024-09-12 14:09 UTC, jmraxa commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
> +    label: ReactNode;
tu pourrais supporter les 2 usages + rajouter un flag `@deprecated` en jsdoc sur `label` pour orienter les utilisateurs vers `children` :D 

C'est un sujet mineur mais qui nous amène quand même à réfléchir comment on gère les breaking changes !

2024-09-13 06:42 UTC, GuillaumeKESTEMAN commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
> +    label: ReactNode;
Ha en effet.
Merci beaucoup, je fais ça 👍

2024-09-13 07:22 UTC, GuillaumeKESTEMAN commented on slash/react/src/List/ClickList/ClickItem/ClickItem.client.tsx
> +    label: ReactNode;
Resolved in https://github.com/AxaFrance/design-system/pull/469/commits/4ee19d74233de9613fe3e82fed84c21a07ff8043

2024-09-13 08:05 UTC, jmraxa approved these changes

2024-09-20 13:03 UTC, Nourelayne approved these changes

2024-09-20 13:04 UTC, merged