feat(radio): ajout d'un label pour le composant RadioSelect
AxaFrance/design-system pull request #491
Opened 2024-08-30 13:35 UTC by letaaz

2024-08-30 14:02 UTC, buddyvegas requested changes

2024-08-30 14:02 UTC, buddyvegas commented on slash/react/src/Form/Radio/Client/RadioSelect.tsx
> +      <fieldset>
il faudrait pas ajouter de fieldset ici
le group de radio devrait pouvoir être dans un fieldset plus grand selon les besoin des applications

2024-08-30 14:12 UTC, buddyvegas commented
la branche `feature/client/radio-select-with-label` a été créé sur le repo du design-system
normalement il faut forker depuis un repo perso

cf CONTRIBUTING.md :

## Comment contribuer

1. **Fork du Projet :** Commencez par forker le projet vers votre compte GitHub.

2. **Cloner le Projet :** Clonez le projet depuis votre compte vers votre machine locale.

2024-08-30 14:13 UTC, buddyvegas commented
si y'a besoin d'un fieldset, il faudrait voir pour ajouter un composant Fieldset indépendant du reste qui gère
avec une prop `required` (pour le petit *)  et une prop `legend` obligatoire

2024-08-30 14:21 UTC, letaaz commented on slash/react/src/Form/Radio/Client/RadioSelect.tsx
> +      <fieldset>
Ok, je le retire (pas de besoin pour l'instant sur le fieldset)

2024-08-30 14:24 UTC, letaaz commented
> la branche `feature/client/radio-select-with-label` a été créé sur le repo du design-system normalement il faut forker depuis un repo perso
> 
> cf CONTRIBUTING.md :
> 
> ## Comment contribuer
> 1. **Fork du Projet :** Commencez par forker le projet vers votre compte GitHub.
> 2. **Cloner le Projet :** Clonez le projet depuis votre compte vers votre machine locale.



> la branche `feature/client/radio-select-with-label` a été créé sur le repo du design-system normalement il faut forker depuis un repo perso
> 
> cf CONTRIBUTING.md :
> 
> ## Comment contribuer
> 1. **Fork du Projet :** Commencez par forker le projet vers votre compte GitHub.
> 2. **Cloner le Projet :** Clonez le projet depuis votre compte vers votre machine locale.

My bad, merci pour le rappel.
On garde quand même celle-là ?

2024-08-30 14:41 UTC, buddyvegas commented
> > la branche `feature/client/radio-select-with-label` a été créé sur le repo du design-system normalement il faut forker depuis un repo perso
> > cf CONTRIBUTING.md :
> > ## Comment contribuer
> > 
> > 1. **Fork du Projet :** Commencez par forker le projet vers votre compte GitHub.
> > 2. **Cloner le Projet :** Clonez le projet depuis votre compte vers votre machine locale.
> 
> My bad, merci pour le rappel. On garde quand même celle-là ?

ouais t'inquiète pas de pb c'était vraiment juste pour le rappel

2024-09-02 08:14 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-09-02 08:14 UTC, GuillaumeKESTEMAN commented on slash/css/src/Form/Radio/Client/Radio.stories.ts
> +    container.innerHTML = `<legend class="af-radio__label" aria-label="Quelle ville ?">Quelle ville ?<span aria-hidden="true">&nbsp;*</span></legend><div role="radiogroup" class="af-radio af-radio-se
tes svg ont des `src` en dur par rapport à ton pc

2024-09-02 08:14 UTC, GuillaumeKESTEMAN commented on slash/react/src/Form/Radio/Client/RadioSelect.stories.tsx
> +      control: { type: "object" },
il y a vraiment besoin de le mettre ?
car généralement il détecte bien les types tableau d'objets

2024-09-02 09:08 UTC, letaaz commented on slash/react/src/Form/Radio/Client/RadioSelect.stories.tsx
> +      control: { type: "object" },
Effectivement pas besoin (c'est retiré)

2024-09-02 09:16 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-09-03 07:47 UTC, JLou commented
il ne faut pas hésiter a ajouter des captures de la feature ajoutée :)

2024-09-03 07:50 UTC, JLou approved these changes, later dismissed

2024-09-09 12:09 UTC, fffan64 approved these changes, later dismissed

2024-09-11 07:12 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-09-11 14:33 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-09-12 09:08 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-09-16 08:51 UTC, buddyvegas submitted a review, later dismissed

2024-09-16 08:51 UTC, buddyvegas commented on slash/react/src/Form/Radio/Client/RadioSelect.tsx
> +          <legend className="af-radio__label" aria-label={radioGroupLabel}>
radioGroupLabel est facultatif
on ne peut pas avoir de fieldset sans legend

2024-09-16 08:51 UTC, buddyvegas commented on slash/react/src/Form/Radio/Client/RadioSelect.tsx
>          <div
tu peux ajouter un role="group" ici 
et aria-labelledby sur le label (si existant)

pour ne pas avoir un conflit d'id utilise useId() pour le label
`const labelid = useId()`

2024-09-16 08:52 UTC, buddyvegas commented on look-and-feel/react/src/Form/Radio/RadioSelect.tsx
> +          <span className="af-radio__label" id={optionId} aria-label={label}>
pas utile le aria-label ici
ton texte va être lu 2 fois sinon

2024-09-20 06:53 UTC, GuillaumeKESTEMAN approved these changes

2024-09-23 14:21 UTC, JovaanB approved these changes

2024-09-23 14:21 UTC, merged

2024-09-23 14:22 UTC, fffan64 approved these changes