feat(alert): pass button for action [Look and Feel]
AxaFrance/design-system pull request #510
Opened 2024-09-16 15:49 UTC by samuel-gomez-axa

Permettre au composant Alert (Look and Feel) de passer un bouton ou un lien d'action

> note : amélioration de l'accessibilité (sémantique et rôle)

🚨BREAKING CHANGE🚨
La prop "**link**" devient "**action**", on peut dorénavant lui passer un type "Link" ou un type "Button".

![image](https://github.com/user-attachments/assets/1547e8ae-6de7-43f5-a7cc-bf9965b69415)

2024-09-17 06:27 UTC, jmevel approved these changes, later dismissed

2024-09-17 07:27 UTC, fffan64 approved these changes, later dismissed

2024-09-17 07:48 UTC, letaaz approved these changes, later dismissed

2024-09-17 08:36 UTC, jmraxa commented on look-and-feel/react/src/Alert/Alert.tsx
> +export type AlertType = keyof typeof alertTypes;
**question :** pourquoi pas tout simplement un enum ? Il servirait à la fois de type et de valeur :
```typescript
export enum AlertType {
    Validation = "validation",
    Error = "error",
    Warning = "warning",
    Information = "information",
    Neutral = "neutral"
}
```

2024-09-17 08:46 UTC, buddyvegas requested changes

2024-09-17 08:46 UTC, buddyvegas commented on look-and-feel/react/src/Alert/Alert.tsx
> +        aria-label="hidden"
faudrait plutôt mettre `aria-hidden="true"`
là le lecteur d'écran va lire "hidden" :)

2024-09-17 08:52 UTC, samuel-gomez-axa commented on look-and-feel/react/src/Alert/Alert.tsx
> +        aria-label="hidden"
bien vu c'est une erreur 😄

2024-09-17 09:05 UTC, samuel-gomez-axa commented on look-and-feel/react/src/Alert/Alert.tsx
> +export type AlertType = keyof typeof alertTypes;
D'une manière générale, j'évite les enums pour les raisons citées ici :
https://react-typescript-cheatsheet.netlify.app/docs/basic/troubleshooting/types/#enum-types
https://www.youtube.com/watch?v=jjMbPt_H3RQ
Et il y a d'autres ressources sur le net qui en parle

2024-09-17 09:10 UTC, samuel-gomez-axa commented on look-and-feel/react/src/Alert/Alert.tsx
> +        aria-label="hidden"
c'est corrigé, merci

2024-09-17 09:32 UTC, jmraxa commented on look-and-feel/react/src/Alert/Alert.tsx
> +export type AlertType = keyof typeof alertTypes;
oki

2024-09-17 11:04 UTC, fffan64 submitted a review, later dismissed

2024-09-17 11:49 UTC, pplancq submitted a review, later dismissed

2024-09-17 11:49 UTC, pplancq commented on look-and-feel/react/src/Alert/Alert.tsx
> +export const alertTypes = {
Pourquoi ne pas utiliser un enum ? ou un objectFreeze ?

2024-09-17 11:49 UTC, pplancq commented on look-and-feel/react/src/Alert/Alert.tsx
> +type Headings = "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
En théorie le titre d'un Alert ne devrait jamais être un h1 car en a11y il est conseillé de ne mettre qu'un seul h1 par page.

2024-09-17 11:49 UTC, pplancq commented on look-and-feel/react/src/Alert/Alert.tsx
> +  type = alertTypes.information,
il faudrait mettre le mettre remplacement dans la fonction `getIconFromType`

2024-09-17 12:39 UTC, samuel-gomez-axa commented on look-and-feel/react/src/Alert/Alert.tsx
> +export const alertTypes = {
cf la réponse à Jean-Marc

2024-09-17 12:40 UTC, samuel-gomez-axa commented on look-and-feel/react/src/Alert/Alert.tsx
> +type Headings = "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
oui effectivement, j'ai hésité à mettre le h1, je l'enlève

2024-09-17 12:56 UTC, pplancq commented on look-and-feel/react/src/Alert/Alert.tsx
> +export const alertTypes = {
OKi pour les enum sa me va. par contre dans le cas d'objet qui serve d'enum j'aime bien utilisé `Object.freeze({})` sa s'utilise comme un objet js classique sauf que l'on ne peut rien modifier.

2024-09-18 06:44 UTC, jmevel approved these changes

2024-09-18 10:42 UTC, fffan64 approved these changes

2024-09-19 08:03 UTC, buddyvegas approved these changes

2024-09-19 08:06 UTC, merged