feat(Loader): improve client loader accessibility
AxaFrance/design-system pull request #531
Opened 2024-10-02 21:02 UTC by Nourelayne

2024-10-03 07:45 UTC, fffan64 submitted a review, later dismissed

2024-10-03 07:45 UTC, buddyvegas requested changes

2024-10-03 07:45 UTC, buddyvegas commented on look-and-feel/react/src/Loader/Loader.tsx
> +    aria-label="Loading"
il ne faut pas mettre "loading" en aria-label, c'est ce qui sera lu par les lecteurs d'écran
tu peux mettre "Chargement en cours" par défaut et mettre le label en props si un texte spécifique doit être mis à la place

2024-10-03 07:48 UTC, Nourelayne commented on look-and-feel/react/src/Loader/Loader.tsx
> +    aria-label="Loading"
En effet, c'est une belle amélioration :)

2024-10-03 07:50 UTC, samuel-gomez-axa commented on look-and-feel/react/src/Loader/Loader.tsx
> +    role="status"
pour le loader de l'ancien toolkit, on avait fait autrement : 
https://github.com/AxaFrance/react-toolkit/blob/master/packages/loader/src/Loader.tsx
@buddyvegas @MartinWeb qu'en pensez-vous ?

2024-10-03 11:41 UTC, buddyvegas commented on look-and-feel/react/src/Loader/Loader.tsx
> +    role="status"
j'ai pour habitude d'utiliser la même chose que sur le toolkit
mais je crois qu'il y a un piège avec le role="alert" pour certain lecteur d'écran
@MartinWeb tu nous en avais déjà parlé non ?

2024-10-04 07:22 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/Loader/Loader.tsx
>  type Props = ComponentPropsWithRef<"input"> & {
Je ne vois pas pourquoi récupérer les props d'input sachant qu'ils ne sont jamais utilisés ? (je sais que ce n'est pas toi qui l'a fait mais je trouve cela plutôt étrange 😅)
Il faudrait peut-être remplacer `input` par `div` (peut-être que tu pourrais même récupérer la prop `ariaLabel` depuis div et donc ne pas avoir à le déclarer ici et ensuite déstructurer le reste des props dans div (ce qui t'évitera aussi de définir ariaLabel à la main comme prop de div L16 et rendre le composant plus permissif)

2024-10-04 07:45 UTC, Nourelayne commented on look-and-feel/react/src/Loader/Loader.tsx
>  type Props = ComponentPropsWithRef<"input"> & {
L'attribut aria-label existe aussi au niveau de input, mais t'as bien raison il faut le remplacer par div car ça n'a pas de sens, c'est une remarque qui a été remonté par @buddyvegas également.

Je vais faire ce changement, et déstructurer le reste des props sur la première div, c'est une bonne idée.

2024-10-04 08:54 UTC, buddyvegas approved these changes

2024-10-04 08:54 UTC, buddyvegas commented on look-and-feel/react/src/Loader/Loader.tsx
>  type Props = ComponentPropsWithRef<"input"> & {
pourquoi omponentPropsWithRef<"input"> ? on est pas sur un input mais une div
il faudrait remplacer par "div" ici
et du coups pas la peine d'ajouter la prop ariaLabel, elle existe déjà dans les props de l'élément div

2024-10-04 08:55 UTC, fffan64 approved these changes

2024-10-04 09:00 UTC, GuillaumeKESTEMAN approved these changes

2024-10-04 09:01 UTC, merged