feat(accordion): add component
AxaFrance/design-system pull request #533
Opened 2024-10-07 14:23 UTC by JLou

fixes #6

2024-10-07 14:41 UTC, GuillaumeKESTEMAN reviewed
Il manque la déclaration des composants react dans l'index.ts de slash

2024-10-07 14:41 UTC, GuillaumeKESTEMAN commented on slash/react/src/Accordion/Accordion.spec.tsx
> +    expect(screen.getByText("My collapse content")).not.toBeVisible();
il faut aussi vérifier l'existence du titre non ?

2024-10-07 14:41 UTC, GuillaumeKESTEMAN commented on slash/react/src/Accordion/Accordion.spec.tsx
> +  });
quelle différence avec le test précédent ?

2024-10-07 15:19 UTC, JLou commented on slash/react/src/Accordion/Accordion.spec.tsx
> +  });
aucune, my bad

2024-10-07 15:19 UTC, JLou commented
> Il manque la déclaration des composants react dans l'index.ts de slash

yep, je m'en suis rendu compte apres le push, et j'ai corrigé asap

2024-10-07 15:23 UTC, JLou commented on slash/react/src/Accordion/Accordion.spec.tsx
> +    expect(screen.getByText("My collapse content")).not.toBeVisible();
on peut. Mais c'est pas super utile car ca revient a tester HTML/ton browser. J'ai rajouté la ligne ca coute rien 👍

2024-10-07 15:23 UTC, JLou commented
@GuillaumeKESTEMAN j'ai fix les pb que tu avais remonté :)

2024-10-08 06:34 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-10-08 06:34 UTC, GuillaumeKESTEMAN commented on slash/react/src/Accordion/Accordion.spec.tsx
> +    expect(screen.getByText("My collapse content")).not.toBeVisible();
il faut aussi vérifier l'existence du titre non ?

2024-10-10 07:17 UTC, MartinWeb requested changes

2024-10-10 07:17 UTC, MartinWeb commented on slash/react/src/Accordion/Body.tsx
> +  const panel = React.useRef<HTMLDivElement>(null);
à quoi te sert la ref exactement ?

2024-10-10 07:17 UTC, MartinWeb commented on slash/react/src/Accordion/Body.tsx
> +      id={id}
idem pour les id, on a un besoin spécial à les avoir ?

2024-10-10 07:28 UTC, GuillaumeKESTEMAN commented on slash/css/doctor-storybook.log
il y a un problème de version de package en local pour le storybook 😆

2024-10-10 07:35 UTC, JLou commented on slash/react/src/Accordion/Body.tsx
> +  const panel = React.useRef<HTMLDivElement>(null);
rien, viré

2024-10-10 07:35 UTC, JLou commented on slash/react/src/Accordion/Body.tsx
> +      id={id}
nope, c'etait utile dans une itération précedente

2024-10-10 07:36 UTC, JLou commented on slash/css/doctor-storybook.log
raaaah mince, c'est le changement de branches entre sb v8 et celle ci qui laisse trainer des fichiers.

2024-10-10 07:36 UTC, JLou commented on slash/css/doctor-storybook.log
cleaned

2024-10-10 07:38 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-10-10 07:52 UTC, MartinWeb approved these changes, later dismissed

2024-10-10 12:21 UTC, GuillaumeKESTEMAN approved these changes

2024-10-11 07:09 UTC, MartinWeb approved these changes

2024-10-11 08:00 UTC, merged