feat(modal): refacto et correctif bug methode close
AxaFrance/design-system pull request #576
Opened 2024-10-29 15:22 UTC by tbeghin

2024-11-04 07:57 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/ModalClient/Modal.hook.ts
> +      }
```suggestion
      if ((event.target as HTMLElement).tagName !== "DIALOG") {
        return;
      }
      
      if (onClickOutside) {
        onClickOutside();
        setIsOpen(false);
      } else {
        handleCloseModal();
      }
```

2024-11-04 07:57 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/ModalClient/Modal.stories.tsx
> +import { ModalContainer as Modal } from "./Modal.container";
il faudrait rajouter un index.ts pour gérer ce renommage car il est en doublon ici et dans le index.ts de L&F react

2024-11-04 07:57 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/ModalClient/__tests__/Modal.test.tsx
> +    const dialog = container.querySelector(".af-modal");
et avec un getByRole ce ne serait pas plus simple ?

2024-11-04 07:57 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/ModalClient/__tests__/Modal.test.tsx
> +      .parentNode?.parentNode?.querySelector("button");
getByRole ?

2024-11-04 07:57 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/ModalClient/__tests__/Modal.test.tsx
> +      const actionButton = screen.getByText(actions[actionType].text);
un getByRole serait mieux pour être sûr d'être un bouton

2024-11-04 07:57 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/index.ts
> +export type { ButtonAction as ModalButtonAction } from "./ModalClient/type";
ce serait plus simple de tout exporter depuis un `./Modal/index.ts` (renommer le dossier serait pas mal aussi maintenant qu'on a séparer le slash et le L&F)

2024-11-04 09:18 UTC, guizahui commented on look-and-feel/react/src/ModalClient/Modal.container.tsx
Petite question pourquoi en pas avoir utiliser le usePortal de react ? C'est typiquement fait pour ce genre de cas ;)

2024-11-04 09:18 UTC, guizahui commented on look-and-feel/react/src/ModalClient/Modal.container.tsx
> +        document.body.style.overflow = "hidden";
Tu pourrais utiliser un guard clauses pour gérer ce cas, et ne pas rendre la modal si isOpen est à false ;)
De plus, toutes la logique ne serait plus dans le useEffect, en règle générale il faut utiliser avec modération les useEffect pour éviter les effets de bords 😃

2024-11-04 09:18 UTC, guizahui commented on look-and-feel/react/src/ModalClient/Modal.container.tsx
> +  const { handleClickOutside, handleKeyDown, handleCloseModal } = useModal({
je pense que la modal ne devrait pas porter d'intelligence ou de logique de hook, c'est préférable de controler la modal sur le composant où il est encapsulé

2024-11-04 09:18 UTC, guizahui commented on look-and-feel/react/src/ModalClient/Modal.stories.tsx
>          {...props}
en mettant un spread de props tu autorises l'envoie de n'importe qu'elle props dans ton composant et si tu mets un spread de props en premier ça veut dire que tu permets la réécriture sur une props du meme nom ;)

2024-11-06 08:11 UTC, JLou requested changes

2024-11-06 08:11 UTC, JLou commented on look-and-feel/react/src/ModalClient/type.ts
> +  hasCloseBtn?: boolean;
```suggestion
  hasCloseButton?: boolean;
```

2024-11-06 08:11 UTC, JLou commented on look-and-feel/react/src/ModalClient/type.ts
> +  isOpen: boolean;
On essaie de garder le nom des props des composants HTML natifs, et dans une modale c'est `open`
```suggestion
  open: boolean;
```

2024-11-06 08:11 UTC, JLou commented on look-and-feel/react/src/ModalClient/__tests__/Modal.test.tsx
> +      actionButton?.click();
utiliser `userEvent` plutot

2024-11-06 09:11 UTC, JLou submitted a review, later dismissed

2024-11-06 09:19 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/package.json
> +    "@types/react-dom": "^18.2.24",
vraiment aucun moyen de le mettre dans les devs deps ?

2024-11-06 09:19 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/ModalClient/Modal.stories.tsx
> +        onClickOutside={() => console.log("close outside modal")}
Plutôt que de mettre des console.log utilise plutôt les actions : https://storybook.js.org/docs/essentials/actions#via-storybooktest-fn-spy-function

2024-11-06 09:26 UTC, tbeghin commented on look-and-feel/react/package.json
> +    "@types/react-dom": "^18.2.24",
Nope

2024-11-06 09:49 UTC, GuillaumeKESTEMAN approved these changes

2024-11-06 09:58 UTC, a-pourrier approved these changes

2024-11-06 10:04 UTC, merged