feat(Title): encompass Title into header tag to improve accessibility
AxaFrance/design-system pull request #583
Opened 2024-11-05 14:34 UTC by GuillaumeKESTEMAN

Issue : https://github.com/AxaFrance/design-system/issues/580

2024-11-05 16:01 UTC, letaaz commented on look-and-feel/css/src/Title/Title.scss
> +  &--xl .af-title__title {
```suggestion
  &--xl &__title {
```
Applicable sur tout le fichier

2024-11-05 16:01 UTC, letaaz commented on look-and-feel/react/src/Title/Title.tsx
> +    <HLevel className={componentClassName}>
**question**: Est ce vraiment une amélioration d'accessibilité d'avoir une `div` comme enfant d'un `h` ?

2024-11-06 07:47 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/Title/Title.tsx
> +    <HLevel className={componentClassName}>
J'ai juste échangé la div avec le heading car c'est plus simple en effet.
L'alternative possible serait que le header soit un display grid comme ça je peux manipuler facilement les emplacements de chaque élément.
Qu'en penses-tu ?

2024-11-06 08:08 UTC, JLou commented on look-and-feel/react/src/Title/Title.tsx
> +    <HLevel className={componentClassName}>
pourquoi ne pas plutot avoir une structure du genre ?
```html
<header>
  <svg .../>
   <h1>Title</h1>
   <p>
     le sous titre
  </p>
  </header>

2024-11-06 08:11 UTC, JLou requested changes

2024-11-06 08:11 UTC, JLou commented on look-and-feel/react/src/Title/Title.tsx
> +
pas vraiment utile de mettre ca dans un memo. Y a probablement plus d'overhead que si tu compute a chaque render

2024-11-06 08:25 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/Title/Title.tsx
> +
En effet, j'avais juste déplacé la logique qui était dans le composant enfant 👍

2024-11-06 08:28 UTC, GuillaumeKESTEMAN commented on look-and-feel/react/src/Title/Title.tsx
> +    <HLevel className={componentClassName}>
Ca me parait plus logique en effet.
N'ayant pas fait la formation accessibilité j'ai juste suivi la demande qui était d'englober dans un h1.
Je vais demander à Samuel mais je préfère ta solution au h1 parent actuel.

2024-11-07 08:46 UTC, letaaz approved these changes, later dismissed

2024-11-12 09:44 UTC, samuel-gomez-axa approved these changes, later dismissed

2024-11-13 15:42 UTC, mandaniainarandriampanana approved these changes

2024-11-13 16:16 UTC, JLou approved these changes

2024-11-14 08:42 UTC, samuel-gomez-axa approved these changes

2024-11-14 08:44 UTC, merged