feat(slash): add Link Component
AxaFrance/design-system pull request #598
Opened 2024-11-18 09:12 UTC by pplancq

**Description**

Implémentation du composant `Link` pour slash, pour ce composant j'ai fait le choix de suffixer la class css par `af-slash` car `af-link` sembler déjà exister (bien que le composant non) et je ne voulais pas occasionner de break ou parasiter les autres class css.

Le composant implémente le style décrit ici https://zeroheight.com/4b1e27a45/v/latest/p/657e74-link/b/7443f5

- Pour les icones le composant fonctionne avec les `glyphicon `mais aussi les `svg`.

- Le composant `Link `permet de surcharger automatiquement l'attribut `rel `de la balise `a` par `noopener noreferrer` si la `target `vaut `_blank`

- Le composant `Link `est interopérable facilement avec des lib de routage tel que `react-router-dom`

```typescript
import { Link as RouterLink } from "react-router-dom";

export const LinkExample = () => (
  <Link component={RouterLink} to="/contact">
    Go to Contact Page
  </Link>
);
```

2024-11-18 09:24 UTC, samuel-gomez-axa commented on slash/react/src/Link/__tests__/Link.test.tsx
> +    expect(link.tagName).toStrictEqual("BUTTON");
on autorise le fait de mettre un bouton ? mais les props du genre target, rel, etc ... sont compatibles ?

2024-11-18 09:48 UTC, GuillaumeKESTEMAN commented on slash/css/src/Link/Link.scss
> +  }
Ce sera fait dans cette PR ?
Si oui on peut mettre la PR en draft en attendant le changement, sinon pas besoin de le mettre car une autre PR s'en chargera.

2024-11-18 09:48 UTC, GuillaumeKESTEMAN commented on slash/css/src/slash.scss
> +@use "Link/Link";
```suggestion
@use "./Link/Link";
```

2024-11-18 09:51 UTC, pplancq commented on slash/react/src/Link/__tests__/Link.test.tsx
> +    expect(link.tagName).toStrictEqual("BUTTON");
Je suis d'accord ici remplacer le `a` par un `button `n'a aucun sens, le test et la pour illustrer le fonctionnement de la props `component`, car je ne voulait pas installer en dev `react-router-dom `pour le test qui en plus aurait été un peut plus complexe

2024-11-18 09:54 UTC, pplancq commented on slash/css/src/Link/Link.scss
> +  }
Je ne sais pas encore tous dépend de quand j'aurais le retour des ux/ui sur le commentaire que j'ai mis dans le figma.
je ne pense pas que ce sois pertinent de mettre en draf juste pour ca sachant que la règles ici ne fait rien.

si j'ai une réponse avant la fin de la PR je l'ajoute sinon ce sera une PR de fix.

2024-11-18 09:55 UTC, pplancq commented on slash/css/src/slash.scss
> +@use "Link/Link";
il faudrait harmoniser ce fichier justement car un coup ou a les `./` un coups non.

2024-11-18 10:00 UTC, GuillaumeKESTEMAN commented on slash/css/src/slash.scss
> +@use "Link/Link";
Je suis d'accord 👍

2024-11-18 10:02 UTC, pplancq commented on slash/css/src/slash.scss
> +@use "Link/Link";
done

2024-11-18 10:08 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-11-18 14:17 UTC, samuel-gomez-axa approved these changes, later dismissed

2024-11-19 07:59 UTC, a-pourrier approved these changes, later dismissed

2024-11-21 11:12 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-11-21 14:23 UTC, samuel-gomez-axa commented on slash/css/src/Link/Link.scss
> +    text-decoration: underline;
pourquoi mettre un underline sur un état disabled ?

2024-11-21 14:24 UTC, samuel-gomez-axa commented on slash/react/src/Link/Link.mdx
> +```tsx title="test.js"
c'est quoi " title="test.js" " ?

2024-11-21 14:26 UTC, samuel-gomez-axa commented on slash/react/src/index.ts
> +export { Link, type LinkProps } from "./Link/Link";
il n'y a pas vraiment d'intérêt à exposer le type

2024-11-21 14:29 UTC, samuel-gomez-axa commented on slash/css/src/Link/Link.scss
> +  text-align: start;
ce n'est pas la valeur par défaut ? pourquoi la redéclarer ici ?

2024-11-21 14:31 UTC, samuel-gomez-axa commented on slash/css/src/Link/Link.scss
> +  text-decoration: underline;
idem c'est le style par défaut

2024-11-21 14:33 UTC, pplancq commented on slash/css/src/Link/Link.scss
> +    text-decoration: underline;
Alors sa n'est pas visible sur le zeroheight https://zeroheight.com/4b1e27a45/v/latest/p/657e74-link mais dans la maquette figma il y a un underline sur un lien disabled.
Après pour en avoir parlé avec les US il est fort probable qu'on ne l'utilise pas.

2024-11-21 14:34 UTC, pplancq commented on slash/react/src/Link/Link.mdx
> +```tsx title="test.js"
c'est un copier coller qui viens des autre fichier mdx je ne suis pas un grand expert de storiebook j'ai donc suivis les fichier existant.

2024-11-21 14:36 UTC, pplancq commented on slash/react/src/index.ts
> +export { Link, type LinkProps } from "./Link/Link";
Justement si car comme le LinkProps à besoin d'un argument il est être utile de l'avoir pour d'autre composant afin de bien spécifier l'élément de surcharge Link de react router par exemple.

2024-11-21 14:37 UTC, pplancq commented on slash/css/src/Link/Link.scss
> +  text-align: start;
Si mais comme j'ai fais un `all: unset` je n'ai plus ce style. J'ai fait sa afin d'être sur de pas avoir de style parasite.

2024-11-21 14:37 UTC, pplancq commented on slash/css/src/Link/Link.scss
> +  text-decoration: underline;
idem `all: unset`

2024-11-21 15:23 UTC, GuillaumeKESTEMAN commented on slash/react/src/index.ts
> +export { Link, type LinkProps } from "./Link/Link";
Et un simple `ComponentProps<typeof Link>` ne suffit pas à correctement obtenir `LinkProps` ?

2024-11-21 15:32 UTC, pplancq commented on slash/react/src/index.ts
> +export { Link, type LinkProps } from "./Link/Link";
Alors oui est non, sur le Link reste un 'a' sa passe mais quand je veux changer par le Link de react router `ComponentProps<typeof Link<RouterLink>>` ne passe pas, ou en tous cas j'ai déjà eu des erreur avec.

2024-11-21 15:35 UTC, GuillaumeKESTEMAN commented on slash/react/src/index.ts
> +export { Link, type LinkProps } from "./Link/Link";
Ha ok

2024-11-21 15:57 UTC, samuel-gomez-axa commented on slash/css/src/Link/Link.scss
> +  text-align: start;
pourquoi ne pas avoir simplement mis ? :
```css
all: initital;
```

2024-11-21 16:18 UTC, samuel-gomez-axa commented on slash/react/src/index.ts
> +export { Link, type LinkProps } from "./Link/Link";
ok

2024-11-22 07:56 UTC, pplancq commented on slash/css/src/Link/Link.scss
> +  text-align: start;
l'avantage du `all: unset;` c'est que `unset` prend en compte les propriétés héritées la ou le `initial` n'en tien pas compte. Mais dans les 2 cas je suis obligé de remettre les propriétés `test-align` et `text-decoration` car elles sont impacté par le `all`.

2024-11-22 15:01 UTC, samuel-gomez-axa commented on slash/css/src/Link/Link.scss
> +  text-align: start;
ok ça marche

2024-11-22 15:01 UTC, samuel-gomez-axa commented on slash/react/src/Link/Link.mdx
> +```tsx title="test.js"
c'est à supprimer je pense

2024-11-22 15:02 UTC, samuel-gomez-axa submitted a review, later dismissed

2024-11-22 15:52 UTC, pplancq commented on slash/react/src/Link/Link.mdx
> +```tsx title="test.js"
j'ai vérifié cela ne change rien dans le storiebook j'ai donc retiré.

2024-11-22 15:53 UTC, pplancq commented on slash/react/src/Link/__tests__/Link.test.tsx
> +    expect(link.tagName).toStrictEqual("BUTTON");
Pour éviter la confusion j'ai changé un peut le test en créer un faux composant Link pouvant provenir d'une lib de routing quelconque comme react router ou autre?

2024-11-22 15:57 UTC, samuel-gomez-axa approved these changes, later dismissed

2024-11-25 15:05 UTC, a-pourrier approved these changes, later dismissed

2024-12-05 09:26 UTC, JLou commented on slash/css/src/Link/Link.scss
Si tu fais un `all:unset` ca ne force pas a mettre du style sur chaque état possible ? Genre active et visited qui sont absents ici

2024-12-05 09:27 UTC, JLou commented on slash/react/src/Link/Link.tsx
> +import "@axa-fr/design-system-slash-css/dist/Link/Link.css";
Il faut plutot importer le scss ici pour qu'a la build finale il n'y ai pas de doublon de css

2024-12-05 09:31 UTC, samuel-gomez-axa commented on slash/react/src/Link/Link.tsx
> +  ReactNode,
type

2024-12-05 09:31 UTC, samuel-gomez-axa commented on slash/react/src/Link/__tests__/Link.test.tsx
> +import { PropsWithChildren } from "react";
type

2024-12-05 09:33 UTC, JLou commented on slash/react/src/Link/Link.stories.tsx
> +      if (type === "/public/edit.svg") return <Svg src={editIcons} />;
Meme dans une story essayons de faire du code propre:
```suggestion
      if (type === "/public/save.svg") {
        return <Svg src={saveIcons} />;
      }
      if (type === "/public/edit.svg") {
        return <Svg src={editIcons} />;
      }
```

2024-12-05 09:35 UTC, pplancq commented on slash/css/src/Link/Link.scss
non justement ca `unset` l'élément mais pas ses pseudo l'élément. du coup si tu veux tous `unset` il faut faire
```scss
.class {
  all: unset;
  &:hover,
  &:focus,
  &:... {
    all: unset;
  }
}
```

2024-12-05 09:44 UTC, JLou requested changes

2024-12-05 09:44 UTC, JLou commented on slash/css/src/Link/Link.scss
J'ai testé et ca enlève bien les pseudos élements également.
Si tu veux check : https://codepen.io/JLoupiote/pen/azodpyE

2024-12-05 10:04 UTC, pplancq commented on slash/css/src/Link/Link.scss
étrange moi ca ne le fait pas sur mon exemple: https://codepen.io/pplancq/pen/YPKwNOg

2024-12-05 11:10 UTC, johnmeunier commented on slash/css/src/Link/Link.scss
On a fait quelques tests. Si ca unset bien toutes les pseudo classe si elles n'ont pas été setté à la main avant. En gros sur un lien tu fais un :hover volontairement ça le laissera, par contre si tu as pas touché au :visited ça le cassera.

Surrement la même chose pour les pseudo éléments.

2024-12-06 14:59 UTC, pplancq commented on slash/css/src/Link/Link.scss
Bon but initial été de remove le style appliqué avec et d'appliquer cette technique aux autres composant dans el but de s'affranchir d'utiliser un reset CSS. Mais cela peux faire parti d'une réflexion à part, j'ai donc retiré le` all: unset`.

2024-12-06 15:02 UTC, pplancq commented on slash/react/src/Link/Link.tsx
> +  ReactNode,
done

2024-12-06 15:03 UTC, pplancq commented on slash/react/src/Link/__tests__/Link.test.tsx
> +import { PropsWithChildren } from "react";
done

2024-12-06 15:04 UTC, pplancq commented on slash/react/src/Link/Link.stories.tsx
> +      if (type === "/public/edit.svg") return <Svg src={editIcons} />;
done

2024-12-06 15:31 UTC, pplancq commented on slash/react/src/Link/Link.tsx
> +import "@axa-fr/design-system-slash-css/dist/Link/Link.css";
je suis pas fan d'imposé le scss mais soit je change on pourra en redisquer dans un autre point.

2024-12-06 15:39 UTC, samuel-gomez-axa approved these changes, later dismissed

2024-12-06 15:44 UTC, GuillaumeKESTEMAN approved these changes

2024-12-09 09:17 UTC, samuel-gomez-axa commented on slash/react/src/Accordion/CollapseCard.tsx
> +import type { DetailsHTMLAttributes, ReactNode } from "react";
ce n'est pas vraiment dans le scope de la PR , non ?

2024-12-09 09:19 UTC, pplancq commented on slash/react/src/Accordion/CollapseCard.tsx
> +import type { DetailsHTMLAttributes, ReactNode } from "react";
non mais comme j'ai du rebase pour résoudre un conflit cela ma ramener une coquille qui à été merge de la main donc je corrige.

2024-12-09 09:44 UTC, samuel-gomez-axa commented on slash/react/src/Accordion/CollapseCard.tsx
> +import type { DetailsHTMLAttributes, ReactNode } from "react";
ok

2024-12-09 09:44 UTC, samuel-gomez-axa approved these changes

2024-12-16 10:55 UTC, johnmeunier approved these changes

2024-12-16 13:00 UTC, johnmeunier commented
Hum j'y pense, Link c'est déjà un composant react-router, ca va poser problème et des gymnastiques pour rien ?

2024-12-16 13:01 UTC, JLou approved these changes

2024-12-16 13:19 UTC, pplancq commented
> Hum j'y pense, Link c'est déjà un composant react-router, ca va poser problème et des gymnastiques pour rien ?

Alors oui je suis d'accord mais le zeroheight nomme un lien Link
Après j'ai toujours eu cette habitude car avec le lib material le composant de lien s'appel Link aussi

```typescript
import { Link as RouterLink } from "react-router-dom";

export const LinkExample = () => (
  <Link component={RouterLink} to="/contact">
    Go to Contact Page
  </Link>
);
```

2025-01-22 12:57 UTC, johnmeunier approved these changes

2025-02-03 14:24 UTC, merged