feat: publish storybook for lnf
AxaFrance/design-system pull request #633
Opened 2024-11-29 08:07 UTC by fffan64

add conf to deploy LnF storybook

2024-11-29 08:38 UTC, jmevel submitted a review, later dismissed

2024-11-29 13:04 UTC, JLou requested changes
Je pense que la config de gitversion doit changer aussi. Je n'ai pas fait les modifs de mémoire.

2024-11-29 13:12 UTC, fffan64 commented
added gitversion config

2024-12-04 14:47 UTC, samuel-gomez-axa approved these changes

2024-12-04 14:50 UTC, GuillaumeKESTEMAN approved these changes

2024-12-04 14:54 UTC, JLou approved these changes

2024-12-04 14:55 UTC, merged