docs: create a release guide
AxaFrance/design-system pull request #680
Opened 2024-12-17 08:27 UTC by MartinWeb

Create a release guide.

2024-12-17 08:36 UTC, pplancq submitted a review, later dismissed

2024-12-17 08:38 UTC, fffan64 approved these changes, later dismissed

2024-12-17 10:04 UTC, a-pourrier submitted a review, later dismissed

2024-12-17 14:45 UTC, samuel-gomez-axa submitted a review, later dismissed

2024-12-18 07:47 UTC, JLou requested changes

2024-12-18 07:47 UTC, JLou commented on RELEASE-GUIDE.md
> +
```suggestion
First of all, before releasing a new version, you need to create a release candidate. A RC is not stable yet but can be tested by the users.

```

2024-12-18 07:47 UTC, JLou commented on RELEASE-GUIDE.md
> +
Donnner le nom exact des branches (confusion possible entre agent/slash ou look-and-feel/lookandfeel/apollo)

2024-12-18 07:47 UTC, JLou commented on RELEASE-GUIDE.md
> +When you are ready to candidate release the version, you can create a tag.
```suggestion
If it's the first time you release candidate this new version, you don't need to commit anything. But you can still commit some changes on this branch, for example, after testing the first release candidate and realizing that you need to fix something.
When you are ready to candidate release the version, you can create a tag.
```

2024-12-18 08:31 UTC, MartinWeb commented on RELEASE-GUIDE.md
> +
done

2024-12-18 08:46 UTC, JovaanB approved these changes

2024-12-18 09:12 UTC, samuel-gomez-axa approved these changes

2024-12-18 09:56 UTC, JLou approved these changes

2024-12-18 12:47 UTC, merged