Feature/add form textarea
AxaFrance/design-system pull request #69
Opened 2024-01-12 15:32 UTC by MqtCorentin

[Issue to link](https://github.com/AxaFrance/design-system/issues/27)

2024-01-12 16:26 UTC, samuel-gomez-axa commented on packages/react/src/Form/InputTextarea/TextareaInput.tsx
> +  const inputId = useId();
le useId ne doit servir que si il n'y a pas d'id passé en props (j'ai aussi l'erreur dans le composant TextInput, faut que je corrige :p )

2024-01-12 16:46 UTC, MqtCorentin commented on packages/react/src/Form/InputTextarea/TextareaInput.tsx
> +  const inputId = useId();
Ok, c'est fait :)

2024-01-12 16:54 UTC, MqtCorentin commented on packages/react/src/Form/InputTextarea/TextareaInput.tsx
> +  const inputId = useId();
J'ai fais une PR de fix pour la partie TextInput : https://github.com/AxaFrance/design-system/pull/71

2024-01-16 14:45 UTC, JLou requested changes

2024-01-16 14:45 UTC, JLou commented on packages/react/src/Form/InputTextarea/TextareaInput.tsx
> +    !!children,
```suggestion
    Boolean(children),
```

2024-01-16 14:45 UTC, JLou commented on packages/react/src/Form/InputTextarea/Textarea.mdx
Le MDX est assez pauvre, mais c'est pas grave. 2 options : 
- on essaie ensemble d'avoir un truc un peu mieux dans cette PR
- on crée une issue pour l'améliorer plus tard

Dans tout les cas c'est pas bloquant pour la 1ere release

2024-01-16 15:29 UTC, JLou approved these changes

2024-01-16 15:29 UTC, MartinWeb approved these changes

2024-01-16 15:29 UTC, merged