Document for open source project
AxaFrance/design-system pull request #72
Opened 2024-01-15 07:37 UTC by johnmeunier

fixes #48 
fixes #47

2024-01-15 08:18 UTC, MartinWeb commented on CODE_OF_CONDUCT.md
> +Nous, en tant que participants et contributeurs, nous nous engageons à rendre la participation à notre projet et à notre communauté une expérience sans harcèlement pour tout le monde, indépendamment
```suggestion
En tant que participants et contributeurs, nous nous engageons à rendre la participation à notre projet et à notre communauté une expérience sans harcèlement pour tout le monde, indépendamment de l'âge, de la taille, de l'invalidité, de l'ethnicité, de l'identité de genre et de l'expression, du niveau d'expérience, de l'éducation, du statut socio-économique, de la nationalité, de l'apparence personnelle, de la race, de la religion ou de l'orientation sexuelle.
```

2024-01-15 08:18 UTC, MartinWeb commented on README.md
> +Le projet est en cours de construction et n'est pas réellement utilisable pour le moment. L'idée est de rapatrier les différents projets existants (Dune et [le toolkit](https://github.com/AxaFrance/r
on ne rapatrie pas vraiment Dune, tout du moins ce n'est pas l'idée pour l'instant

2024-01-15 09:22 UTC, johnmeunier commented on README.md
> +Le projet est en cours de construction et n'est pas réellement utilisable pour le moment. L'idée est de rapatrier les différents projets existants (Dune et [le toolkit](https://github.com/AxaFrance/r
Sur le long terme le but c'est de rendre dispo aussi le design system public ? Je voulais transmettre cette idée, tu le tournerais comment ?

2024-01-15 09:24 UTC, johnmeunier commented on CODE_OF_CONDUCT.md
> +Nous, en tant que participants et contributeurs, nous nous engageons à rendre la participation à notre projet et à notre communauté une expérience sans harcèlement pour tout le monde, indépendamment
Done

2024-01-15 14:17 UTC, samuel-gomez commented on CONTRIBUTING.md
> +Le nom des branhes est au soumis à la convention [git flow](https://danielkummer.github.io/git-flow-cheatsheet/index.fr_FR.html).
branches

2024-01-15 14:17 UTC, samuel-gomez commented on README.md
> +Le projet est en cours de construction et n'est pas réellement utilisable pour le moment. L'idée est de rapatrier les différents projets existants (Dune et [le toolkit](https://github.com/AxaFrance/r
plus connu sous le nom de 'Slash' plutôt que 'toolkit'

2024-01-15 14:44 UTC, JLou commented
dans le readme ou dans le contributing, il manque un truc je pense : les commandes nécessaires pour lancer les storybook, dire qu'il faut build le css avant de lancer le storybook react etc

2024-01-15 15:58 UTC, MartinWeb commented on README.md
> +Le projet est en cours de construction et n'est pas réellement utilisable pour le moment. L'idée est de rapatrier les différents projets existants (Dune et [le toolkit](https://github.com/AxaFrance/r
sur le long terme c'est d'avoir le public et l'interne oui, mais de ce que j'avais compris, Dune resterait une sorte de style pour un seul projet à terme. Donc à voir si on mentionne son nom ici ou pas

2024-01-16 08:45 UTC, johnmeunier commented
> dans le readme ou dans le contributing, il manque un truc je pense : les commandes nécessaires pour lancer les storybook, dire qu'il faut build le css avant de lancer le storybook react etc

J'ai initié ça dans le dernier commit, tu en penses quoi ?

2024-01-16 09:06 UTC, SebastienDegodez approved these changes

2024-01-16 13:35 UTC, samuel-gomez submitted a review, later dismissed

2024-01-16 14:38 UTC, JLou requested changes

2024-01-16 14:38 UTC, JLou commented on CONTRIBUTING.md
> +git checkout -b nom-de-ma-branche
```suggestion
git switch -c nom-de-ma-branche
```

2024-01-16 14:38 UTC, JLou commented on CONTRIBUTING.md
> +Le nom des branches est au soumis à la convention [git flow](https://danielkummer.github.io/git-flow-cheatsheet/index.fr_FR.html).
je pense pas que ca soit nécessaire ça. On va pas faire de gitflow et les noms de branches, tant que le gars l'appelle pas main c'est OK :D

2024-01-16 14:39 UTC, johnmeunier commented on CONTRIBUTING.md
> +Le nom des branches est au soumis à la convention [git flow](https://danielkummer.github.io/git-flow-cheatsheet/index.fr_FR.html).
On ne fait pas de git flow

2024-01-16 14:46 UTC, johnmeunier commented on README.md
> +Le projet est en cours de construction et n'est pas réellement utilisable pour le moment. L'idée est de rapatrier les différents projets existants (Dune et [le toolkit](https://github.com/AxaFrance/r
### Look & Feel et Slash

2024-01-16 15:20 UTC, MartinWeb approved these changes

2024-01-16 15:20 UTC, JLou approved these changes

2024-01-16 15:21 UTC, samuel-gomez approved these changes

2024-01-16 15:28 UTC, merged