refactor(form): text input
AxaFrance/design-system pull request #78
Opened 2024-01-16 14:46 UTC by GuillaumeKESTEMAN

Refactor https://github.com/AxaFrance/design-system/pull/50 changes and update `Input Text` stories.

As requested in this comment : https://github.com/AxaFrance/design-system/pull/50#discussion_r1447433458

2024-01-17 09:44 UTC, samuel-gomez commented
en synchro, on s'est dit qu'on pouvait nommer le dossier /Text au lieu de /InputText

2024-01-17 10:42 UTC, GuillaumeKESTEMAN commented
> en synchro, on s'est dit qu'on pouvait nommer le dossier /Text au lieu de /InputText

C'est corrigé 👍

2024-01-19 13:22 UTC, samuel-gomez commented on packages/css/src/Form/Text/Text.stories.ts
> +    input.readOnly = args.readOnly;
il me semble qu'il n'y a pas de majuscule sur readonly sur un élément natif

2024-01-19 13:22 UTC, samuel-gomez commented on packages/css/src/Form/Text/Text.stories.ts
> +    input.className = inputDefaultClassNames.join(" ");
je pense que c'est plutôt class sur un élément natif

2024-01-19 13:28 UTC, samuel-gomez commented on packages/css/src/Form/Text/Text.stories.ts
> +    autoFocus: false,
autofocus

2024-01-19 13:28 UTC, samuel-gomez commented on packages/css/src/Form/Text/Text.stories.ts
> +    readOnly: false,
readonly

2024-01-19 13:29 UTC, samuel-gomez commented on packages/css/src/Form/Text/Text.stories.ts
> +    input.ariaDisabled = args["aria-disabled"];
```suggestion
    input['aria-disabled'] = args["aria-disabled"];
```

2024-01-19 13:38 UTC, samuel-gomez commented on packages/react/src/Form/core/getComponentClassName.ts
> +    .find((it) => Boolean(it));
On ne peut pas juste faire ça ?
```suggestion
    .find(Boolean);
```

2024-01-19 13:39 UTC, samuel-gomez commented on packages/react/src/Form/core/getOptionClassName.ts
> +    .filter((c) => Boolean(c))
On ne peut pas juste faire ça ?
```suggestion
    .filter(Boolean)
```

2024-01-19 13:40 UTC, samuel-gomez commented on packages/react/src/Form/Text/TextInput.tsx
> +  const inputId = id || inputUseId;
Du coup, on a décidé de permettre la chaine vide
```suggestion
  const inputId = id ?? inputUseId;
```

2024-01-19 13:41 UTC, samuel-gomez submitted a review, later dismissed

2024-01-19 13:44 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/core/getComponentClassName.ts
> +    .find((it) => Boolean(it));
En effet ça a l'air de fonctionner 👍

2024-01-19 13:44 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/core/getOptionClassName.ts
> +    .filter((c) => Boolean(c))
En effet ça a l'air de fonctionner 👍

2024-01-19 13:57 UTC, samuel-gomez submitted a review, later dismissed

2024-01-19 14:42 UTC, JLou requested changes

2024-01-19 14:42 UTC, JLou commented on packages/react/src/Form/core/getComponentClassName.ts
> +  return classNameToUse.split(" ").reverse().find(Boolean);
J'ai du mal à voir à quoi sert le `reverse` ici. Peux tu m'éclairer ?

2024-01-19 14:42 UTC, JLou commented on packages/react/src/Form/Text/constants.ts
`constants.ts` c'est a proscrire si possible. Essaie de donner un nom plus descriptif, comme par exemple : `inputTypes.ts`

2024-01-19 14:42 UTC, JLou commented on packages/react/src/Form/Text/constants.ts
> +export const TYPES: HTMLInputTypeAttribute[] = ["text", "email", "password"];
Pas besoin de mettre en caps lock, `inputTypes` c'est plus dans la norme

2024-01-19 14:42 UTC, JLou commented on packages/react/src/Form/Text/TextInput.stories.tsx
> +        Place name <i>optional</i>
si tu veux mettre en évidence le optional, un em/strong est plus adapté. Et de manière général on interdit les balises i/b car elles n'ont aucun sens sémantique.

```suggestion
        Place name <em>optional</em>
```

2024-01-19 14:42 UTC, JLou commented on packages/react/src/Form/Text/TextInput.stories.tsx
> +type Story = StoryObj<React.ComponentProps<typeof TextInput>>;
Il me semble que ca suffit cette syntaxe :

```suggestion
type Story = StoryObj<typeof TextInput>;
```

2024-01-19 14:42 UTC, JLou commented on packages/css/src/Form/Text/TextInput.stories.ts
J'apprécie l'effort d'avoir rendu la story interactive, mais pour la partie CSS je pense pas qu'il faille aller jusque là.
L'idée principale étant de faire un showcase du HTML attendu par le composant.
Avoir quelques props interactives, comme le label, ou le disabled/required pourquoi pas. Mais aller dans le niveau de détail des classes des labels/input c'est probablement pas nécessaire.
Pareil pour l'`id` etc...

Essaie de simplifier pour n'avoir que les "différents états" du composant

2024-01-19 14:51 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/core/getComponentClassName.ts
> +  return classNameToUse.split(" ").reverse().find(Boolean);
Je crois qu'il permet de récupérer la dernière classe d'une liste de classes.
Mais maintenant que tu le dis je pense que faire `classNameToUse.split(" ").trim().pop();` suffirait et serait plus lisible.
Qu'en penses-tu ?

2024-01-19 14:55 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Text/constants.ts
> +export const TYPES: HTMLInputTypeAttribute[] = ["text", "email", "password"];
D'accord, je vais la renommer `inputTypes`.
Comme j'ai vu des constantes en majuscules dans le projet j'ai gardé cette norme.

2024-01-19 14:56 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Text/TextInput.stories.tsx
> +        Place name <i>optional</i>
D'accord, j'avais juste fait un copié collé de https://github.com/AxaFrance/react-toolkit/blob/master/packages/Form/Input/text/README.md?plain=1#L246
Je vais corriger ça 👍

2024-01-19 14:58 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Text/TextInput.stories.tsx
> +type Story = StoryObj<React.ComponentProps<typeof TextInput>>;
En effet, c'est utilisé ici https://github.com/AxaFrance/react-toolkit/blob/master/packages/Form/Input/text/README.md?plain=1#L246
Je vais remplacer

2024-01-22 09:17 UTC, pplancq commented on packages/react/src/Form/Text/Text.tsx
> +  type?: HTMLInputTypeAttribute;
La props type est déjà déclaré dans le type input que l'on étend donc pas besoin de le remettre ici

2024-01-22 09:17 UTC, pplancq commented on packages/react/src/Form/Text/Text.tsx
> +  ({ className, classModifier, type = "text", ...otherProps }, inputRef) => {
pas besoin de récupérer le type ici

2024-01-22 09:17 UTC, pplancq commented on packages/react/src/Form/Text/Text.tsx
> +        type={type}
ici on peut laisse `type="test"` mais il faut juste le placer avant le `{...otherProps}`

2024-01-22 09:17 UTC, pplancq commented on packages/react/src/Form/Text/TextInput.tsx
> +  const inputId = id ?? inputUseId;
mieux vaux utiliser l'opérateur `||` comme cela si l'utilisation mets une chaine vide en id pour que l'on puis avec l'id généré par `useId`

2024-01-22 09:34 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Text/TextInput.tsx
> +  const inputId = id ?? inputUseId;
Je suis d'accord, mais il a été décidé d'utiliser `??`.

2024-01-23 15:16 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/core/getComponentClassName.ts
> +  return classNameToUse.split(" ").reverse().find(Boolean);
`classNameToUse.split(" ").filter(Boolean).at(-1);`

2024-01-24 07:48 UTC, pplancq approved these changes, later dismissed

2024-01-24 08:12 UTC, JLou commented on packages/react/src/Form/Text/Text.tsx
> +        type="test"
C'est normal d'être passé à `test` ?

2024-01-24 09:04 UTC, samuel-gomez commented on packages/css/src/Form/Text/Text.stories.ts
> +    const input = document.createElement("input");
à terme il faudra peut-être mutualiser ce code pour d'autres stories de champ

2024-01-24 09:44 UTC, GuillaumeKESTEMAN commented on packages/react/src/Form/Text/Text.tsx
> +        type="test"
Non, c'est réglé 😅

2024-01-24 09:49 UTC, pplancq approved these changes

2024-01-24 09:53 UTC, JLou approved these changes

2024-01-24 10:14 UTC, merged