feat(Pass): add Pass input component
AxaFrance/design-system pull request #81
Opened 2024-01-18 08:48 UTC by JLou

Fixes #21

2024-01-19 07:51 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-01-19 07:51 UTC, GuillaumeKESTEMAN commented on .vscode/settings.json
> +  },
Automatic vscode update or voluntary update?

2024-01-19 08:07 UTC, JLou commented on .vscode/settings.json
> +  },
voluntary, I like eslint fixing shit for me without having to ask

2024-01-19 08:19 UTC, GuillaumeKESTEMAN commented on .vscode/settings.json
> +  },
👍

2024-01-22 08:27 UTC, fffan64 approved these changes

2024-01-22 09:42 UTC, pplancq requested changes

2024-01-22 09:42 UTC, pplancq commented on packages/css/package.json
> +    "@storybook/test": "7.6.5",
Pourquoi ce changement ici ? 
Cela génère  l'installation de 2 versions de storiebook la 7.6.5 dans la package css et la 7.6.7 dans le package react qui s'installe dans le node_module global?

2024-01-22 09:42 UTC, pplancq commented on packages/react/src/Form/Pass/Pass.tsx
> +          role={type === "password" ? "password" : "textbox"}
le rôle ne s'adapte pas automatique en fonction du type ?
d'ailleurs autre question est vraiment utile de change le rôle de l'input, on est dans un composant password donc même si l'utilisateur rend visible le champ password ?

2024-01-22 09:42 UTC, pplancq commented on packages/react/src/Form/Pass/PassInput.tsx
> +  const finalId = id ?? inputId;
```suggestion
  const finalId = id || inputId;
```
en cas de chaine vide l'id générer sera utilisé

2024-01-22 09:47 UTC, JLou commented on packages/react/src/Form/Pass/PassInput.tsx
> +  const finalId = id ?? inputId;
cf #79

2024-01-22 09:48 UTC, JLou commented on packages/react/src/Form/Pass/Pass.tsx
> +          role={type === "password" ? "password" : "textbox"}
bonne question, c'est l'existant. @MartinWeb  mr l'expert accessibilité est ce que tu sais si il faut changer le role ici ?

2024-01-22 09:50 UTC, pplancq commented on packages/react/src/Form/Pass/PassInput.tsx
> +  const finalId = id ?? inputId;
yes mais que fait on si l'utilisateur envois une chaine vide ?
Oki l'issue propose un warning pour prévenir mais ici on utilise pas le code de issue donc pourquoi ?

2024-01-22 10:07 UTC, JLou commented on packages/css/package.json
> +    "@storybook/test": "7.6.5",
reliquat de moi qui me bat avec les packages SB incompatibles.
Bon par contre on pourrait parfois avoir des pbs car on peut avoir des versions de packages SB incompatibles (ex: on monte le package addon dans react, mais pas le html dans le package css).

2024-01-22 10:09 UTC, JLou commented on packages/react/src/Form/Pass/PassInput.tsx
> +  const finalId = id ?? inputId;
on attend que qqun prenne l'issue pour changer le behaviour.
On en a discuté la semaine derniere, mais grosso modo, si qqun a mis `id=""` c'est probablement pour une raison.
C'est pour ca qu'on ne force pas un id dans ce cas.

Et le code de l'issue c'est un exemple, pas l'implem finale forcément

2024-01-22 12:47 UTC, pplancq commented on package-lock.json
> -      "integrity": "sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==",
C'est nouveau que npm retire les `resolved` et `integrity` de tous les packages ?

2024-01-22 12:49 UTC, pplancq commented on packages/css/package.json
> +    "@storybook/test": "7.6.5",
Le fichier de config de SB n'a pas pour vocation à dire qu'elles sont les addon à charger ?

2024-01-24 09:59 UTC, JLou commented on packages/css/package.json
> +    "@storybook/test": "7.6.5",
si, mais ca pointe juste vers le dossier dans le node_modules. Pas vers une version précise

2024-01-24 10:00 UTC, JLou commented on package-lock.json
> -      "integrity": "sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==",
dunno, je suis en version de npm `10.1.0`

2024-01-24 10:16 UTC, pplancq commented on package-lock.json
> -      "integrity": "sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==",
c'est chelou ca je suis en npm 10.2.5 et j'ai pas ca.

2024-01-24 10:20 UTC, pplancq commented on package-lock.json
> -      "integrity": "sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==",
Il semble que ce sois un bug de npm. https://stackoverflow.com/questions/75224019/resolved-and-integrity-go-missing-in-package-lock-json
du coups `npm cache clean -f` et `npm install`

2024-01-24 10:40 UTC, JLou commented on package-lock.json
> -      "integrity": "sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==",
ca n'a rien changé chez moi

2024-01-24 10:48 UTC, pplancq commented on package-lock.json
> -      "integrity": "sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==",
et si tu rollback la package-lock ?

2024-01-24 11:08 UTC, JLou commented on package-lock.json
> -      "integrity": "sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EAlCNUzRDYDdFwFYUKvXcIA==",
apres moults essais, et en supprimant le node modules ca a revert le change

2024-01-24 12:35 UTC, pplancq commented on packages/css/package.json
> +    "@storybook/test": "7.6.5",
Après si vraiment il n'y a que storiebook qui fait chier avec ses version on peut toujours lui retirer les carrets mais attention à bien mettre les même version sur les 2 packages css et react.

2024-01-24 12:36 UTC, pplancq commented on packages/react/src/Form/Pass/Pass.tsx
> +          role={type === "password" ? "password" : "textbox"}
A la limite on peut laisser comme ca et changer plus tard.

2024-01-24 12:36 UTC, pplancq approved these changes

2024-01-24 13:03 UTC, GuillaumeKESTEMAN approved these changes

2024-01-24 14:22 UTC, merged