feat(button-client): add Button client component
AxaFrance/design-system pull request #89
Opened 2024-01-23 14:28 UTC by fffan64

Added a client button (look'n feel)

![image](https://github.com/AxaFrance/design-system/assets/35838907/17ea1825-5b69-4660-beb0-d473e07424c2)

2024-01-23 14:42 UTC, JLou commented
The design spec: https://www.figma.com/file/21801ytpBZM2hBkaxGdzgW/01.-Composants-Espace-Client?type=design&node-id=3542-60506&mode=design&t=2NY22o94zZefHAHB-0

2024-01-26 07:01 UTC, pplancq requested changes

2024-01-26 07:01 UTC, pplancq commented on packages/css/src/Button/Button.client.scss
> +.af-btn-client {
ici il faudrait retirer le -client de la class.

2024-01-26 07:01 UTC, pplancq commented on packages/css/src/Button/Button.client.scss
> +  }
les glyphicon sont également utilisé coté LF ?
car coté slash elles sont déprécier et seront plus tard remplacer par les icons MUI.

2024-01-26 07:01 UTC, pplancq commented on packages/css/src/Button/Button.client.scss
> +  &--hasIconLeft {
ici le ne pense pas que 2 naming de class soit utile

2024-01-26 07:01 UTC, pplancq commented on packages/css/src/Button/Button.client.scss
> +@use "sass:color";
sass:color n'est pas utiliser sur ce fichier donc le use n'est pas utile.

2024-01-26 07:01 UTC, pplancq commented on packages/react/src/Button/Button.agent.stories.tsx
> +  title: "Components/ButtonAgent",
Je pense que pour les storie il faudrait que le dossier de premier niveau soit le nom du design system
Ce qui donnerais:
Lock'n feel/Components/Button

Du coup coté Slash il faudrait faire de même dans une RP dédier.

2024-01-26 07:01 UTC, pplancq commented on packages/react/src/Button/Button.client.tsx
> +  iconRight?: string;
ici il faudrait mieux injecter un ReactNode, comme cela ce sera à l'utilisateur d'injecter l'icon qui lui convient
Ce qui changera un peu l'implementation plus bas.
Mais cela rendrera la migration vers les icons MUI plus facile.

2024-01-26 07:01 UTC, pplancq commented on packages/react/src/Button/Button.client.tsx
> +  ...args
ici je préfère le nom de props cela correspond plus à  la nomenclature react (mais c'est juste un pref perso)

2024-01-26 07:01 UTC, pplancq commented on packages/react/src/Button/Button.client.tsx
> +};
suite à mon commentaire sur la props en React Node je ferais comme ceci
```suggestion
type ButtonProps = {
  variant?: Variants;
  iconLeft?: ReactNode;
  iconRight?: ReactNode;
} & ComponentPropsWithoutRef<"button">;

export const ButtonClient = ({
  children,
  className,
  disabled,
  variant,
  iconLeft,
  iconRight,
  ...props
}: PropsWithChildren<ButtonProps>) => {
  return (
    <button
      className={cx(
        "af-btn-client",
        variant && `af-btn-client--${args.variant.toString()}`,
        disabled && 'af-btn-client--disabledé,
        iconLeft && 'af-btn-client--hasiconLeft',
        iconRigh && 'af-btn-client--hasiconRight't,
        className,
      )}
      type="button"
      disabled={disabled}
      {...props}
    >
      {iconLeft}
      {children}
      {iconRight}
    </button>
  );
};
```

2024-01-26 09:26 UTC, pplancq requested changes

2024-01-26 09:26 UTC, pplancq commented on package.json
> +    "eslint-import-resolver-typescript": "^3.6.1",
j'ai oublié de te dire qu'il faut install le package dans les packages css et react directement.
du coup il faudra que tu :
```bash
npm r eslint-import-resolver-typescript
cd package/css
npm i -D eslint-import-resolver-typescript
cd ../react
npm i -D eslint-import-resolver-typescript
```

2024-01-26 09:26 UTC, pplancq commented on packages/react/package.json
> +    "@emotion/styled": "^11.11.0",
c'est requis pour `@mui/icons-material` ?

2024-01-26 10:36 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +.af-btn-client {
comme vu, on le garde pour le moment (conflit de load css entre le client et agent car meme nom)

2024-01-26 10:37 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  }
removed, en effet, on utilisera des icons probablement de material ui

2024-01-26 10:37 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  &--hasIconLeft {
merci

2024-01-26 10:37 UTC, fffan64 commented on packages/react/src/Button/Button.agent.stories.tsx
> +  title: "Components/ButtonAgent",
done, merci

2024-01-26 10:40 UTC, fffan64 commented on packages/react/package.json
> +    "@emotion/styled": "^11.11.0",
malheureusement, oui :(

2024-01-26 10:43 UTC, fffan64 commented on package.json
> +    "eslint-import-resolver-typescript": "^3.6.1",
done, merci

2024-01-26 11:04 UTC, pplancq commented on packages/react/package.json
> +    "@emotion/styled": "^11.11.0",
Pourtant c'est 2 lib son tagger comme optional dans @mui/material
"peerDependencies": {
    "@emotion/react": "^11.5.0",
    "@emotion/styled": "^11.3.0",
    "@types/react": "^17.0.0 || ^18.0.0",
    "react": "^17.0.0 || ^18.0.0",
    "react-dom": "^17.0.0 || ^18.0.0"
  },
  "peerDependenciesMeta": {
    "@types/react": {
      "optional": true
    },
    "@emotion/react": {
      "optional": true
    },
    "@emotion/styled": {
      "optional": true
    }
  },
  
source https://github.com/mui/material-ui/blob/v5.15.6/packages/mui-material/package.json#L89

A tu tester sans ?

2024-01-26 12:45 UTC, fffan64 commented on packages/react/package.json
> +    "@emotion/styled": "^11.11.0",
j'étais persuade d'avoir tester sans, et il me les réclamait, (je me rappelle du message d'erreur), mais je viens de retester a l'instant et en effet, c ok ...
je testais plusieurs truc, j'ai pu du faire gaffe a ce que j'importais.

du coup bien vu ! je fais le ménage merci :)

2024-01-26 12:50 UTC, pplancq commented on packages/react/package.json
> +    "@emotion/styled": "^11.11.0",
Parfait ça du coup le seul truc qui est dommage c'est que `@mui/icons-material` à a peerDep `@mui/material` qui est requise.
Sa aurait pu être cool d'avoir les icons material sans les composants.

Je me demande s'il n'y a pas une lib plus petite pour juste les icones

2024-01-26 12:55 UTC, fffan64 commented on packages/react/package.json
> +    "@emotion/styled": "^11.11.0",
ya ca : https://developers.google.com/fonts/docs/material_icons?hl=fr#getting_icons
en font

2024-01-26 12:59 UTC, fffan64 commented on packages/react/package.json
> +    "@emotion/styled": "^11.11.0",
https://fonts.google.com/icons?hl=fr

2024-01-26 13:00 UTC, pplancq commented on packages/react/package.json
> +    "@emotion/styled": "^11.11.0",
Après question est ce que c'est à nous de fournir les icons material auquel cas il faut qu'on les re export tous ?
Sinon on met `@mui/icons-material` en peerDep optional est c'est au client de dl la lib d'icons

2024-01-30 11:10 UTC, GuillaumeKESTEMAN commented on packages/react/src/Button/Button.client.mdx
> +<ArgsTable story="Button" />
Désormais on utilise `<Controls />` à la place `<ArgsTable />`, ça permet d'avoir plusieurs blocs de control dans un même MDX.
https://storybook.js.org/docs/api/doc-block-controls

2024-01-30 16:35 UTC, fffan64 commented on packages/react/src/Button/Button.client.mdx
> +<ArgsTable story="Button" />
done

2024-01-31 07:23 UTC, GuillaumeKESTEMAN commented on packages/css/src/Button/Button.agent.stories.ts
> +  title: "Components/Button Agent",
Peut-être diviser comme sur le storybook d'AF.Client en mettant un dossier agent et un dossier client ?

![image](https://github.com/AxaFrance/design-system/assets/81412571/58b3631f-a365-438f-8fbd-dd49df659f07)

2024-01-31 07:35 UTC, fffan64 commented on packages/css/src/Button/Button.agent.stories.ts
> +  title: "Components/Button Agent",
deja fait en fait :
https://github.com/AxaFrance/design-system/pull/89#discussion_r1467279686

![image](https://github.com/AxaFrance/design-system/assets/35838907/9f217f39-be14-44fa-8e12-a1f96e6a6aa5)

et comme indique, il faudra faire de même pour les comp slash, dans une PR dédiée

2024-01-31 07:38 UTC, pplancq commented on packages/react/package.json
> +    "classix": "^2.1.35",
Attention à bien rebase depuis la main on fait une PR pour remove classix

2024-01-31 07:38 UTC, pplancq commented on packages/react/src/Button/Button.client.tsx
> +        iconRight ? "af-btn-client--hasiconRight" : undefined,
```suggestion
        iconLeft && "af-btn-client--hasiconLeft",
        iconRight && "af-btn-client--hasiconRight" ,
```
classNames n'ajoutera pas les classes si iconLeft/Right sont undifined

2024-01-31 07:55 UTC, GuillaumeKESTEMAN commented on packages/css/src/Button/Button.agent.stories.ts
> +  title: "Components/Button Agent",
Autant pour moi 😅

2024-01-31 08:05 UTC, fffan64 commented on packages/react/package.json
> +    "classix": "^2.1.35",
en fait j'avais bien rebase la main, mais vu que je l'utilisais dans mon code aussi, ca la rerajoute, la je lai vire.

2024-01-31 08:09 UTC, fffan64 commented on packages/css/src/Button/Button.agent.stories.ts
> +  title: "Components/Button Agent",
np

2024-01-31 08:18 UTC, pplancq approved these changes

2024-01-31 08:20 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-01-31 08:25 UTC, pplancq requested changes
correction stylelint à faire voir gihub action

2024-01-31 08:44 UTC, pplancq commented
A oui on a validé l'utilisation de @mui/icons-material dans le package react.
Par contre il faudra ajouter un `export * from '@mui/icons-material'` dans le fichier `client.ts` afin que les consomateur import les icons depuis @axa-fr/design-system-react

2024-01-31 10:53 UTC, GuillaumeKESTEMAN approved these changes, later dismissed

2024-01-31 10:58 UTC, samuel-gomez commented on config/eslint.config.js
> +        "extensions": [".js", ".jsx", ".ts", ".tsx"]
pourquoi a t-on besoin d'ajouter les extensions js ?

2024-01-31 10:59 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &--hasiconLeft {
pour la version Slash, on n'avait pas le choix mais pour la version client, je préconise plutot l'utilisation du has css

2024-01-31 11:01 UTC, samuel-gomez commented on packages/react/package.json
> +    "@mui/icons-material": "^5.15.6",
ce n'est pas une peer dependencies ?

2024-01-31 11:02 UTC, fffan64 commented on config/eslint.config.js
> +        "extensions": [".js", ".jsx", ".ts", ".tsx"]
a cause des icones mui material, c du typescript donc on en a besoin

2024-01-31 11:16 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  font-size: 1em;
plutot des rem

2024-01-31 11:16 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  border-radius: 8px;
il faudrait créer un token

2024-01-31 11:17 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  position: relative;
pourquoi a t-on besoin d'une position relative ?

2024-01-31 11:17 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  transition: all 0.2s linear;
le all est à éviter

2024-01-31 11:19 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  cursor: pointer;
la bonne pratique est de mettre le cursor pointer uniquement pour les liens

2024-01-31 11:20 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &:focus {
plutot utiliser le :focus-visible

2024-01-31 11:21 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  color: common.$table-inverse-color;
$table-inverse-color ?

2024-01-31 11:22 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +    background-color: common.$color-deep-sapphire;
on pourrait commencer à utiliser les css variables

2024-01-31 11:23 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &--disabled,
plutot utliser un selecteur lié à l'attrobit aria-disabled ou disabled , pas de modifier pour ce cas

2024-01-31 11:25 UTC, samuel-gomez commented on config/eslint.config.js
> +        "extensions": [".js", ".jsx", ".ts", ".tsx"]
les icones material sont en js ?

2024-01-31 11:48 UTC, fffan64 commented on config/eslint.config.js
> +        "extensions": [".js", ".jsx", ".ts", ".tsx"]
oui pardon en js sinon on a ca :

![image](https://github.com/AxaFrance/design-system/assets/35838907/df6b2866-9fbe-4904-8a15-dcb8223fec05)

2024-01-31 12:05 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  &--hasiconLeft {
tu ferais comment pour le selector ? car je suis pas familier avec.
le type des icones etant generic (ReactNode), pas certains de savoir comment faire

2024-01-31 12:14 UTC, fffan64 commented on packages/react/package.json
> +    "@mui/icons-material": "^5.15.6",
mis en peer dependency

2024-01-31 12:26 UTC, fffan64 commented on packages/react/package.json
> +    "@mui/icons-material": "^5.15.6",
mais now ca plante:
![image](https://github.com/AxaFrance/design-system/assets/35838907/e370a870-aebc-4a22-b788-8aceaf1804a3)

que faire ?

2024-01-31 12:28 UTC, pplancq commented on packages/css/src/Button/Button.client.scss
> +  cursor: pointer;
A bon pourtant presque tout les bouton on le cursor pointer

2024-01-31 12:30 UTC, pplancq commented on packages/react/package.json
> +    "@mui/icons-material": "^5.15.6",
même après un `npm r @mui/icons-material` et `npm i --save-peer @mui/icons-material` ?

2024-01-31 12:32 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  position: relative;
reste de code lors de la reprise button agent, v le virer

2024-01-31 12:34 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  cursor: pointer;
je ne comprends pas ce comment, sur un bouton, je vuex toujours le cursor: pointer

2024-01-31 12:40 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  &:focus {
pourquoi ? ca change le comportement

2024-01-31 12:41 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  color: common.$table-inverse-color;
reliquat du code button agent, v modifier

2024-01-31 12:46 UTC, fffan64 commented on packages/react/package.json
> +    "@mui/icons-material": "^5.15.6",
oui

2024-01-31 12:50 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  transition: all 0.2s linear;
ca fait ce que je veux pour le moment donc c ok

2024-01-31 12:51 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  border-radius: 8px;
pk ? ca apporte quoi ?

2024-01-31 13:08 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  border-radius: 8px;
ça permet d'uniformiser les radius pour les composants et en cas de changement, il faudra simplement modifier le token. De mon point de vue, ça n'a pas de sens de lié le border-radius à la font root avec du rem car il n'y a aucun lien entre les 2

2024-01-31 13:11 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  transition: all 0.2s linear;
désolé mais je ne suis pas en phase, tu peux appliquer les transition uniquement sur ce que tu as besoin

2024-01-31 13:14 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &:focus {
parce que l'on clique sur le bouton, on n'a pas besoin de voir un outline. on en a surtout besoin lorsque l'on fait de tabulation

2024-01-31 13:19 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  &--disabled,
done, je te laisse le soins de resoudre ou pas le comment

2024-01-31 13:19 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  cursor: pointer;
quand tu créés un bouton natif, c'est pas un pointeur de lien que tu as et à juste titre

2024-01-31 13:29 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  border-radius: 8px;
donc je remets 8px et je créé une var dans `common.client.scss` a la place ?

2024-01-31 13:29 UTC, samuel-gomez commented on packages/react/package.json
> +    "@mui/icons-material": "^5.15.6",
et si tu ajoutes @emotion/styled dans les peer-dependencies ?

2024-01-31 14:00 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &--hasiconLeft {
à vrai dire, j'enlèverai toute cette partie de style, on n'a pas vraiment besoin d'ajouter un padding sur l'icone.
plutôt qu'un long discours, je t'ai fait une petite démo : https://codepen.io/gsam59/pen/WNmMWre

2024-01-31 14:08 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &--disabled,
il manque le [aria-disabled="true"] comme selecteur, quand c'est ok tu peux résoudre

2024-01-31 14:34 UTC, fffan64 commented on packages/react/package.json
> +    "@mui/icons-material": "^5.15.6",
vu avec @pplancq c good now, tout en peer dependencies

2024-01-31 14:47 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  border-radius: 8px;
done :)

2024-01-31 15:03 UTC, pplancq approved these changes, later dismissed

2024-01-31 15:06 UTC, GuillaumeKESTEMAN submitted a review, later dismissed

2024-01-31 15:30 UTC, samuel-gomez-axa commented on packages/css/src/Button/Button.client.scss
> +  &--hasiconLeft {
après si tu n'es pas à l'aise sur cette partie, on peut le faire plus tard

2024-01-31 15:31 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &:focus {
non bloquant peut être traité plus tard

2024-01-31 15:32 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  transition: all 0.2s linear;
non bloquant peut être traité plus tard

2024-01-31 15:34 UTC, samuel-gomez submitted a review, later dismissed

2024-01-31 17:11 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  &--hasiconLeft {
ok, j'ai ajuste suivant tes recommandations, tu me diras si ca te va ? merci

2024-01-31 17:23 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  transition: all 0.2s linear;
j'ai modif, tu me diras si t'es ok ? merci

2024-01-31 17:27 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  &:focus {
j'ai modif, tu me diras si t'es ok ? merci

2024-01-31 22:00 UTC, fffan64 commented on packages/css/src/Button/Button.client.scss
> +  &--disabled,
je l'ai rajoute :)

2024-02-01 08:18 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &--hasiconLeft {
ok pour moi merci +1

2024-02-01 08:19 UTC, pplancq approved these changes

2024-02-01 08:20 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  transition: all 0.2s linear;
ok pour moi

2024-02-01 08:21 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &:focus {
ok pour moi

2024-02-01 08:21 UTC, samuel-gomez commented on packages/css/src/Button/Button.client.scss
> +  &--disabled,
top !

2024-02-01 08:22 UTC, samuel-gomez approved these changes
c'est tout bon pour moi , merci pour la PR :)

2024-02-01 10:37 UTC, GuillaumeKESTEMAN approved these changes

2024-02-01 12:57 UTC, merged